### ISSUE TITLE
[1.12.2] Picking up sinking/floating items with right click causes next two right clicks to fail

### ISSUE THREAD

**Issue by Charles445** [CreativeMD/ItemPhysic#101]
Tested wtih CreativeCore_v1.9.71_mc1.12.2 + ItemPhysic_Full_1.4.26_mc1.12.2

Right clicking to pick up an item that is floating or sinking will cause the next two right click block interactions to fail/desync. I've included a video to demonstrate this bug.

https://youtu.be/-WqFcaZ6kXA

If it helps any, this effect is present in CreativeCore_v1.9.67_mc1.12.2 + ItemPhysic_Full_1.4.21_mc1.12.2, but it only causes _one_ right click to fail in that version.

**Comment by Charles445** [comment]
Okay, I think I've figured out what's going on.
The mod cancels right clicks to avoid interacting with blocks under your crosshair when picking up an item.
The problem is, if you were to pick up an item and you _don't_ have a block under your crosshair, the player gets added to the toCancel array even though there is no right click event that needs cancelling.
So this bug also happens when you toss an item into the air and grab it with right click.
It can also cause multiple right clicks to fail if you keep doing it since the array just gets bigger.

**Comment by CreativeMD** [comment]
I fixed it in the newest version. Thanks for your detailed issue report! Hope everything works fine now. New version should be available in a few minutes.
