### ISSUE TITLE
Doesnt warn about missing dependency "CreativeCore"

### ISSUE THREAD

**Issue by thegamerx1** [CreativeMD/ItemPhysic#103]
Minecraft was crashing at startup because i didnt have creative core installed but usually forge warns about this but this time didnt

Example image from internet:
![image](https://user-images.githubusercontent.com/34986564/70558448-33b01700-1b85-11ea-809e-080abc03773f.png)

**Comment by CreativeMD** [comment]
I know but it's not possible in this case, because ItemPhysic requires CreativeCore even before this dependency check is done. There is no way to fix it sorry :(
