### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by ghost** [CreativeMD/ItemPhysic#105]
Forge: x.2847
ItemPhysic: 1.4.29
DoggyTalents: 1.12.2-1.15.1.4

https://paste.dimdev.org/fekujehaya.mccrash

While the first line is about another mod, right under that are 2 lines about this mod, and me updating this mod caused the problem. If I'm in the wrong place please redirect.

Edit: using .28 and .27 results in this error: https://paste.dimdev.org/wuninukewo.mccrash

I feel this may be a multi-pronged problem.

**Comment by CreativeMD** [comment]
I have created a pull request for Doggy Talents, let's hope it will be merged and released soon: https://github.com/percivalalb/DoggyTalents/pull/224

**Comment by CreativeMD** [comment]
This issue has been fixed. Update Doggy Talents.
