### ISSUE TITLE
Conflict between Doggy Talents and Item Physic

### ISSUE THREAD

**Issue by RodrigoTaipe93** [CreativeMD/ItemPhysic#106]
Hello!

There seems to be an issue between Item Physic and Doggy Talents. It happens when I start Minecraft. I'm notifying both authors, just in case.

This is the log:

- https://paste.dimdev.org/exexodidaj.mccrash

**Comment by CreativeMD** [comment]
This is a duplicate of https://github.com/CreativeMD/ItemPhysic/issues/105
