### ISSUE TITLE
Disabling Custom Throw does not correctly revert to vanilla behaviour

### ISSUE THREAD

**Issue by floral-qua-floral** [CreativeMD/ItemPhysic#108]
When using vanilla throw mechanics, items are dropped the instant the drop keybind is pressed. However, with ItemPhysic installed and configured to disable its throwing changes, items are still thrown when the keybind is _released,_ instead. This isn't any sort of game-breaking issue, but it is inconsistent with expected behaviour, and has tripped me up a number of times when I'm trying to drop a stack of items - it's very easy to accidentally release Control before releasing Q, which due to this change causes only a single item to be dropped from the hand instead of the whole stack. I'd be very happy to see this fixed, as it's one of the only things that consistently bothers me when I use this mod.

**Comment by CreativeMD** [comment]
Didn't even know this one. Fixed it in the newest version. Thank you very very much for your help!
