### ISSUE TITLE
Pickup key pickups are blocked by tall grass / other non-solids

### ISSUE THREAD

**Issue by floral-qua-floral** [CreativeMD/ItemPhysic#109]
When Custom Pickup is enabled, items cannot be grabbed through tall grass using the pickup key. This can be a bit of a hassle when items fall into or near grass and other plants, as the player has to either break the grass or stop and crouch to grab the item (or, if sneak pickup is disabled, the player's only option is to break the grass). It would be preferable if items could be grabbed through any tile that doesn't restrict player movement, including tall grass as well as flowers and vines.

**Comment by CreativeMD** [comment]
Very good idea. I added it in the newest version and fixed a couple of other issues related to custom pickup as well.
