### ISSUE TITLE
Item Physics not respecting keepAlive (?)

### ISSUE THREAD

**Issue by DeathRtH** [CreativeMD/ItemPhysic#11]
Using FTB Infinity 1.3.1 with Itemphysics added in, attempting to upgrade the Terra Shatterer from Botania, which works fine without Item physics in. I'm certain Item Physics is somehow circumventing the keepAlive on terra shatterer (and possibly others like AE Crystal seeds).

I can provide a complete modlist if necessary.

**Comment by CreativeMD** [comment]
Will take a look at this.

**Comment by CreativeMD** [comment]
Will be fixed in the next version.
