### ISSUE TITLE
Enhanced Visuals mod breaks when rendering a dropped item tooltip

### ISSUE THREAD

**Issue by Terrahop** [CreativeMD/ItemPhysic#110]
Minecraft: 1.12.2
ItemPhysic: 1.4.31
Enhanced Visuals: 1.3.3
Tough as Nails: 1.12.2-3.1.0.141

It seems rendering a dropped item tooltip messes with [Enhanced Visuals](https://www.curseforge.com/minecraft/mc-mods/enhancedvisuals) and [Tough as Nails](https://www.curseforge.com/minecraft/mc-mods/tough-as-nails). When looking at an item, enhanced visuals for some reason set's it's tough as nails [chill/heat](http://terra.fastmail.com.user.fm/minecraft/minecraft-before.png) effect intensity to the [max](http://terra.fastmail.com.user.fm/minecraft/minecraft-looking.png) preventing me from seeing anything until I look away again.

This might be a problem on Enhanced Visuals Side but not sure, it works fine when I set `showPickupTooltip` to false

**Comment by CreativeMD** [comment]
Released a new version of ItemPhysic which should fix the issue. Thanks for reporting it!
