### ISSUE TITLE
Repeating crash, even after uninstalling the mod keeps happening

### ISSUE THREAD

**Issue by SissyTrashQueen** [CreativeMD/ItemPhysic#114]
MC version: 1.15.2
Forge version: 31.1.43
ItemPhysic Full: v1.4.0
CreativeCore: v2.0.5

[Crash report](https://gist.github.com/slard3/cbcbb753a1997c2ad99361e01a50fec2)

I'm in a singleplayer newly created world (after uninstalling the mod), and for some reason the items try to render as if the mod is still installed?

I uninstalled it because this same crash kept happening with the mod installed and I thought it would stop if I simply remove it lol

**Comment by SissyTrashQueen** [comment]
So, I've just changed the "vanillaRendering" to true in the config and it seems to have fixed it, I think

EDIT: Nope, it didn't [Crash report](https://gist.github.com/slard3/ed9027a34fa110c2d0b7576e8b37ee92)

**Comment by CreativeMD** [comment]
That is extremely weird. Looks like the mod is still installed somehow? Can you send a screenshot of your mods folder?

**Comment by SissyTrashQueen** [comment]
[Crash Report](https://gist.github.com/slard3/2c5f9bab3c7af72adaad876e6375bfeb)

![mod_folder](https://user-images.githubusercontent.com/55768134/79766568-24409780-82f6-11ea-9749-93c1a6d3bca7.jpg)

**Comment by CreativeMD** [comment]
Can move the other folders out of the mod folder and test it again?

**Comment by SissyTrashQueen** [comment]
I've moved the folders out of there and it still crashed.
I'll leave the [latest.log](https://gist.github.com/slard3/82e0fc9c3ef1f40a94d6d24f8c0b67d9) here

**Comment by CreativeMD** [comment]
This gets even more weird. Can you install ItemPhysic Lite and see if it fixes the crash?

**Comment by SissyTrashQueen** [comment]
I think the game is good now, for some reason. I did install the Lite version like a month ago, then changed to the Full version (uninstalling the Lite one) and the crashes began. I had started to think about reinstalling Minecraft to fix this.

**Comment by CreativeMD** [comment]
Ok very weird. I will close this issue for now. Next time I know what to suggest. Hope everything works fine now.
