### ISSUE TITLE
ItemPhysics causes crash for modpack

### ISSUE THREAD

**Issue by Wgairborne** [CreativeMD/ItemPhysic#115]
I've just decided to let you know about this happening with my set of mods, though I'm not really concerned with not being able to have it in the modpack. 

Here's the crash report when inserting it into the mods and launching the game.
https://paste.dimdev.org/nivepekiju.mccrash

**Comment by Wgairborne** [comment]
While fixing another mod, I found that VanillaFix was not updated correctly, but with that updated correctly and the other said mod working fine now (DynamicSurroundings), ItemPhysics still doesn't work. Here is the crash report for this occasion: https://paste.dimdev.org/arataxitab.mccrash

**Comment by CreativeMD** [comment]
Make sure all of my mods are updated. Your ItemPhysic and EnhancedVisuals version are way outdated.
