### ISSUE TITLE
ItemPhysic incompatible with Quark mod

### ISSUE THREAD

**Issue by Geezt435** [CreativeMD/ItemPhysic#116]
Item despawn is not compatible with Quark flashing before item's despawn

Also I found in config that it's 6000, is it count in tick or second?

**Comment by CreativeMD** [comment]
Created an issue in their repository let's hope we can solve this: https://github.com/Vazkii/Quark/issues/2115

**Comment by Geezt435** [comment]
@CreativeMD Thanks for the quick replies, so, I got a way to fix it by making ItemPhysic time before despawning into 2000 instead 6000, the problem is that I don't know if it's second or tick so it still isn't compatible with quark despawn system yet. Quark despawn time is 200 tick

**Comment by CreativeMD** [comment]
Quark does not recognize the modified time from ItemPhysic. Quark's despawn time is the duration the item flashes.

**Comment by CreativeMD** [comment]
This feature is not part of 1.15 and therefore it won't be fixed. Sorry, but there is nothing I can do about that.

**Comment by Geezt435** [comment]
It's ok, it's not bugging me too hard
