### ISSUE TITLE
Item is invisible when touched with soul sand

### ISSUE THREAD

**Issue by Geezt435** [CreativeMD/ItemPhysic#117]
![2020-05-04_12 59 02](https://user-images.githubusercontent.com/46617557/80940692-2258f700-8e13-11ea-8e36-c918d9228250.png)

The string is invisible when it's dropped on soul sand, making it hard to search if I want to pick a certain item

**Comment by CreativeMD** [comment]
Thanks for reporting this issue. It has been fixed in the newest version.
