### ISSUE TITLE
Spinning to fast

### ISSUE THREAD

**Issue by Sebbed04** [CreativeMD/ItemPhysic#12]
when im dropping a normal item its spin to fast. Why...

**Comment by CreativeMD** [comment]
You can configure it in the config file.

**Comment by Sebbed04** [comment]
Thx!! How much do you have on:


    I:despawn=6000

**Comment by Sebbed04** [comment]
CreativeMD This mod is awesome!!!!!!!!!!!! :)

**Comment by CreativeMD** [comment]
6000 is the default, 
it's the number of ticks.
Minecraft has 20 ticks per second
as a result it's 5 mins.

**Comment by Sebbed04** [comment]
So i gonna have... ?Ticks

**Comment by CreativeMD** [comment]
yep, but this doesn't effect the rotation speed :D

**Comment by Sebbed04** [comment]
But what i need to edit.

**Comment by Sebbed04** [comment]
# Configuration file

item {
    B:customPickup=false
    B:customThrow=true
    I:despawn=6000
}

**Comment by CreativeMD** [comment]
#  [range: 0.0 ~ 100.0, default: 1.0]
    S:rotateSpeed=1.0

you will need to download the newest version

**Comment by Sebbed04** [comment]
ItemPhysic 1.1.5  Full dosent work on 1.8

**Comment by CreativeMD** [comment]
you can't do it for 1.8,
it's not supported yet, sorry.

**Comment by Sebbed04** [comment]
:( Plz can you update it to 1.8

**Comment by Sebbed04** [comment]
your best if you can do that!!! :) :+1:

**Comment by Sebbed04** [comment]
I LOVE REALISTIC MODS!!!!!!!!!! :)

**Comment by Sebbed04** [comment]
And this realistic mod is awesome and one of the best realistic mods!

**Comment by CreativeMD** [comment]
yes will add it soon.

**Comment by Sebbed04** [comment]
YOUR AWESOME!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Sebbed04** [comment]
PLZ TELL ME WHEN ITS OUT!!!!! I gonna scream!!!

**Comment by CreativeMD** [comment]
maybe tomrrow

**Comment by Sebbed04** [comment]
YAAAAAY!!!!!!!!!!!!!!!

**Comment by Sebbed04** [comment]
I Love peoples like you. A peoples that makes something cooler! Its too cool. Im telling all my friends to download it and install it but everyone said: Its too hard. and i said: no its easy, spend one hour and its done. but them said: stop talking about that mod, that mod is a tiny mod, everyone here can do this mod. its so easy code.  And i said: you have wrong. :)

**Comment by Sebbed04** [comment]
Do you gonna finish the 1.1.6 version to 1.8 today? thats will be awesome!

**Comment by Sebbed04** [comment]
Do you gonna finish 1.1.6 version to 1.8 today?? if you upload it today it will be awesome!

**Comment by CreativeMD** [comment]
just redownload the newest version for 1.8

**Comment by Sebbed04** [comment]
Thx!
tors 4 jun 2015 kl. 22:39 skrev CreativeMD <notifications@github.com>:

**Comment by Sebbed04** [comment]
AWESOME THATS SO COOL!!!!!!!😀 
THX SO MUCH!!!!!😀

**Comment by Sebbed04** [comment]
IT WORKS GOOD JOB!!!!!!!!!!!!!!! :)

**Comment by Sebbed04** [comment]
Its still spinning fast
:(

**Comment by CreativeMD** [comment]
you have to configure it maybe something like 0.01

**Comment by Sebbed04** [comment]
Og THX!!!!!!!!!!!!!! :)!

**Comment by Sebbed04** [comment]
THX!!!!!!!!!!!!!!!!!
