### ISSUE TITLE
Picking up items from anywhere.

### ISSUE THREAD

**Issue by wenseul** [CreativeMD/ItemPhysic#121]
Not sure what is causing the issue but everyone on my server is able to pick up items through walls at a seemingly infinite range with right click. I have the distance set to 4.0 yet its not working.

**Comment by CreativeMD** [comment]
Which version of the mod are you using? I tested it with the newest version for 1.12 and it works absolutely fine.

**Comment by SissyTrashQueen** [comment]
Minecraft version: 1.15.2
Forge version 31.1.98

ItemPhysic_v1.4.3_mc1.15.2
CreativeCore_v2.0.5_mc1.15.2

I think I've run into this as well.
The config, resetted to default and only changed the custom pickup to true,
```
  "pickup": {
    "customPickup": true,
    "pickupWhenSneaking": true,
    "maximumPickupRange": 5.0,
    "pickupMinedImmediately": false,
    "respectRangeWhenMined": false
  }
```

[Video using the config shown](https://imgur.com/a/DiymWgC)

Any item at any distance, by simply aiming the crosshair at it, you're able to pick it up.

Offtopic: is it possible to hide most of the tooltip and only show the item name? Some mods add a significant amount of text to their item tooltips

**Comment by CreativeMD** [comment]
It's fixed in the newest version. Thanks for reporting this issue!
