### ISSUE TITLE
error during comment_setup phase

### ISSUE THREAD

**Issue by jackg2527** [CreativeMD/ItemPhysic#126]
Hi, 

edit: oops I meant common not 'comment'!

Very happy to see you've updated this awesome mod to 1.16.2! 

Just started the game and this message:

ItemPhysic (itemphysic) encountered an error during the common setup event phase 
net/minecraftforge/event/world/BlockEventsHarvestDropsEvent

I'm using new release (full version) + creative core. Forge 33.0.20, latest.log is attached below.

Many thanks for any help you could provide.
[latest.log](https://github.com/CreativeMD/ItemPhysic/files/5116216/latest.log)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thank you very much for reporting this issue!
