### ISSUE TITLE
When charging up to throw, the drop animation plays multiple times

### ISSUE THREAD

**Issue by BugmanBugman** [CreativeMD/ItemPhysic#127]
https://streamable.com/ygunyo

**Comment by BugmanBugman** [comment]
This wouldn't happen in 1.12 versions, where the drop animation would only play when you threw it.

**Comment by CreativeMD** [comment]
Actually this is a feature. I wanted to add this animation to make the player realize that a throw is charging up. It's also not a drop animation, but the "general interaction" one (same as placing a block for example). Should I really remove it (because i actually think it's better)?

**Comment by BugmanBugman** [comment]
Ahh ok, just wanted to make sure


On Oct 12, 2020, at 12:05 PM, CreativeMD <notifications@github.com> wrote:

﻿

Actually this is a feature. I wanted to add this animation to make the player realize that a throw is charging up.

**Comment by zDragoNzz** [comment]
I think you should add an option to enable or disable it, i don't think that animation looks right for it, maybe the bow animation would fit it better

**Comment by CreativeMD** [comment]
It's not that easy to disable it.

**Comment by zDragoNzz** [comment]
> It's not that easy to disable it.

that's unfortunate, maybe using that bow charging animation if possible would look a lot better

**Comment by CreativeMD** [comment]
That's not how it works unfortunately.
