### ISSUE TITLE
Right click behaviour toggle or deprioritize?

### ISSUE THREAD

**Issue by No3371** [CreativeMD/ItemPhysic#128]
With Psi, we can't right click drops with their CAD (tool). For mods using right clicking drops with specific items in hand as part of gameplay, it'd be a shame to disable the wonderful right click picking experience for this kind of situation.

**Comment by CreativeMD** [comment]
Can you tell me which mod adds this "CAD" (tool). Haven't heard of it before.

**Comment by No3371** [comment]
PSI: [https://www.curseforge.com/minecraft/mc-mods/psi](https://www.curseforge.com/minecraft/mc-mods/psi)
I thought the issue is not related to any specific mod but a more general problem of handling PlayerInteractEvent, but I don't really familiar with Minecraft modding... So it's a compatibility issue? (Just small talk for maybe I'll try making mod soem days)

**Comment by CreativeMD** [comment]
Does it happen without ItemPhysic installed?

**Comment by No3371** [comment]
The problem here is that the mod expect players right click item drops with the tool, then the item will be transformed into something else, but with ItemPhysics installed and custom pickup enabled, items will be picked up right away.

**Comment by CreativeMD** [comment]
Which version are you using 1.12 or 1.16? You could set a pickup key in controls (so itemphysic will not use right click).

**Comment by No3371** [comment]
It works! I did not realize the key binding is a override. Thank you!
