### ISSUE TITLE
[1.16.3] With itemphysics full, fishing rods reel power of fish is too weak

### ISSUE THREAD

**Issue by BugmanBugman** [CreativeMD/ItemPhysic#129]
https://streamable.com/pwubko
As you can see, the fishing rod is not always able to pull the fish item with enough power. In vanilla when you reel back you rod out, the fish drop flies directly towards you.

**Comment by CreativeMD** [comment]
No idea what is supposed to happen. Also not sure if this is related to ItemPhysic ... also I don't think I can fix anything from my end. It's probably a good idea to report the issue to the author of the fishing rod.

**Comment by BugmanBugman** [comment]
https://streamable.com/4c6pv3
Vanilla behavior of the fishing rod makes it so the item flies straight towards you when you reel out. In this video, I tested it with ItemPhysics lite and the behavior was working.

**Comment by BugmanBugman** [comment]
Crap, I just realized I uploaded the wrong video for the first post. My apologies. This is the video of the fishing rod being weird
https://streamable.com/pwubko

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thank you very much for reporting this issue!
