### ISSUE TITLE
[1.16.4] Items get stuck on IE sloped conveyor belts

### ISSUE THREAD

**Issue by Shandoo94** [CreativeMD/ItemPhysic#133]
Item Physics 1.4.10
Forge 34.1.7
IE 4.1.1-128

As the title says. With the new item rendering the items get stuck on IE sloped conveyor belts wich are connected to a horizontal one.

Here is a screenshot:
![2020-12-05_20 47 23](https://user-images.githubusercontent.com/21018028/101266701-bac0ac80-3751-11eb-8725-e703768e3728.png)

**Comment by CreativeMD** [comment]
Actually the rendering cannot cause anything to get stuck. Not sure why this happens. Are you 100% it works without ItemPhysic?

**Comment by Shandoo94** [comment]
When I uninstall ItemPhysic it works as normal. 
I don't know how exactly the converyor belts work, but it could have to do with the way a sloped belt pushes the items a block higher.
It looks like the belt is not realy moving it but rather throwing it in the direction it is facing, and the force is not strong enough for the items to land on the horizontal belt.

**Comment by CreativeMD** [comment]
Can you show me it from the side I want to rebuild it so I can test it myself? I tested it and it worked just fine for me.

**Comment by Shandoo94** [comment]
It is simply a sloped belt to a horizontal one.

![2020-12-20_21 31 27](https://user-images.githubusercontent.com/21018028/102723772-d65bb380-430a-11eb-84b2-0753b4bf95c8.png)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
