### ISSUE TITLE
ItemPhysics causes items to frantically shake when placed into Astral Sorcery blocks.(yes the bug is at it again)

### ISSUE THREAD

**Issue by kuroyure** [CreativeMD/ItemPhysic#134]
its the same as #80 but on the most recent versions, *horray!*

**Comment by CreativeMD** [comment]
What is the most recent version? I need more details? Is it 1.12 or 1.16?

**Comment by Wolfstar1010** [comment]
I'm also having this issue playing in 1.16.4. 
Item Physics Version 1.4.8
Astral version 1.13.4

**Comment by CreativeMD** [comment]
https://github.com/HellFirePvP/AstralSorcery/pull/1563

**Comment by CreativeMD** [comment]
I guess this is fixed now. If not just let me know here.
