### ISSUE TITLE
[1.16.4] Items disappear when throwing

### ISSUE THREAD

**Issue by Quanty-Q** [CreativeMD/ItemPhysic#135]
I found an issue trying to play with **ItemPhysic Mod** and **Weapon Throw Mod** at the same time. For some reason every time you **drop an item** with letter Q the item just **disappears**.... gone forever.
So it is impossible to play with those 2 mods together... Please FIX!

**Comment by CreativeMD** [comment]
Disable customthrow in the config (in the file "itemphysic.json" in the config folder). That might fix your issue.

**Comment by CreativeMD** [comment]
I will close this issue for now ...
