### ISSUE TITLE
oldRotation, vanillaRendering, and rotateSpeed are ignored

### ISSUE THREAD

**Issue by ChloeDawn** [CreativeMD/ItemPhysic#138]
**ItemPhysic version:** [v1.4.14_mc1.16.4](https://www.curseforge.com/minecraft/mc-mods/itemphysic/files/3144607)
**CreativeCore version:** [v2.0.10_mc1.16.4](https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3128357)
**Forge version:** 1.16.5-36.0.0 (can also be produced on 1.16.4-35.1.37)

Changing these settings does not change how the mod renders items
However, `showPickupTooltip` and `disableThrowHUD` work as expected

*This was reproduced with only ItemPhysic and CreativeCore present*

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thank you very much for reporting this issue!
