### ISSUE TITLE
Incompatible with Arclight

### ISSUE THREAD

**Issue by ZekerZhayard** [CreativeMD/ItemPhysic#141]
Related to https://github.com/IzzelAliz/Arclight/issues/50

[Arclight](https://github.com/IzzelAliz/Arclight) is a Bukkit server implementation on Forge using Mixin.
It will crash if ItemPhysic installed with it.

`debug.log`: https://paste.ubuntu.com/p/75hdRWS75p/

Arclight Version: [1.16.5-1.0.12-SNAPSHOT-bcf3f33](https://ci.appveyor.com/api/buildjobs/b6s2gcrmrc86vy5j/artifacts/build%2Flibs%2Farclight-forge-1.16-1.0.12-SNAPSHOT.jar)
ItemPhysic Version: [v1.4.15_mc1.16.5](https://edge.forgecdn.net/files/3172/384/ItemPhysic_v1.4.15_mc1.16.5.jar)

I noticed that both [Arclight](https://github.com/IzzelAliz/Arclight/blob/bcf3f3342d04db82178853685f559937b55e7891/arclight-common/src/main/java/io/izzel/arclight/common/mixin/core/entity/item/ItemEntityMixin.java#L49-L54) and [ItemPhysic](https://github.com/CreativeMD/ItemPhysic/blob/c14bb8b46a7a313d4805720f782cbd4c52208827/src/main/resources/META-INF/itemtransformer.js#L87-L112) modify the method `net.minecraft.entity.item.ItemEntity:func_70097_a`, so it caused a crash.

I think ItemPhysic's modification is too radical, which may cause it to potentially conflict with other mods. Since a large number of Core Mods have changed from using ASM to using Mixin, I suggest ItemPhysic to make corresponding changes (Use partial modifications instead of replacing the entire method). Thanks!

**Comment by CreativeMD** [comment]
Should be fixed in the newest version! Sorry that it took me so long, I had to do some other things first.
