### ISSUE TITLE
Items don't flow in water over hoppers

### ISSUE THREAD

**Issue by wcdanh2** [CreativeMD/ItemPhysic#142]
While trying to setup a vanilla style item sorter where items are dropped via a dropper into water and then flow over hoppers the items keep getting stuck on top of hoppers that are full rather than continuing on to the next hopper in the line.

The type of item sorter: https://youtu.be/ruw1elYIQo4?t=25
![2021-02-17_23 42 01](https://user-images.githubusercontent.com/986594/108307291-89198800-717b-11eb-80bf-146489104f91.png)

**Comment by CreativeMD** [comment]
I mean things like that are very likely to happen if the physics of the items are actually changed. So I guess either make all items float or remove the mod. Besides that you could also use ItemPhysic Lite which only changes the way items are rendered rather their physics.
