### ISSUE TITLE
Tooltip Appears Over Inventory GUI

### ISSUE THREAD

**Issue by luxlacis** [CreativeMD/ItemPhysic#143]
When looking at an item to pickup and having the tooltips enabled, it shows the tooltip text (name of item) over the inventory. MC version is 1.16.5

https://i.imgur.com/TXiM8r7.png
https://i.imgur.com/tLB88jj.png

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
