### ISSUE TITLE
Villagers don't pick up food?

### ISSUE THREAD

**Issue by EliotWL** [CreativeMD/ItemPhysic#146]
MC v 1.16.5 mod v 1.4.17,  It might not be this mod in particular but seems the most likely.  For whatever reason, my villagers don't pick up dropped food ever.  Just ignore it most of the time, occasionally seeing it and looking at it but never picking it up.  Any chance you've seen something like that before?

**Comment by CreativeMD** [comment]
I don't think ItemPhysic changes any behavior related to it.
