### ISSUE TITLE
getNext function not found

### ISSUE THREAD

**Issue by sfiomn** [CreativeMD/ItemPhysic#147]
Hello,

I see this error at the start of a server that has ambient sound, itemPhysics and CreativeCore. All with the latest version.

I'm using the latest forge version as well (36.1.4)

https://gist.github.com/sfiomn/04e8aaf0b672ed1742acaed63efe3d49

**Comment by sfiomn** [comment]
Having only those mods:
- CreativeCore 2.1.0
- FriendlyEndermite 1.0.2
- ItemPhysics 1.4.17

I see also this error

https://gist.github.com/sfiomn/4df42d9bd8d707324303067457eaec7b

**Comment by ChloeDawn** [comment]
This issue is preventing item drops from being picked up when `customPickup` is disabled.

**Comment by CreativeMD** [comment]
Fixed in the newest version!
