### ISSUE TITLE
Texture Pack conflict

### ISSUE THREAD

**Issue by IronlegacyXVII** [CreativeMD/ItemPhysic#148]
I have vanilla additions and I had found out that it was conflicting with the mod however I didn't want to out right delete the pack. What would happen is that items would drop vertical. Is there something I can edit or delete to make these function together?
[Vanilla_Additions_1.8.3.zip](https://github.com/CreativeMD/ItemPhysic/files/6289307/Vanilla_Additions_1.8.3.zip)

**Comment by CreativeMD** [comment]
I don't think I can do anything about that. Just make sure everything works fine if this resourcepack is not installed (so it's not caused by something else).
