### ISSUE TITLE
EnderIO, possibly add ignore clause? spinning item

### ISSUE THREAD

**Issue by plaguewolf** [CreativeMD/ItemPhysic#15]
enderio has 3 items, Experience Obelisk, Aversion Obelisk, and Attractor Obelisk, that have items as part of the render, and they spin spastically with your mod installed.

i believe whats going on is that EnderIO's renderer uses minecraft physics to render the part of the machine that has the item on it, and as such item physics tries to apply to it, but it gets reset at its "animation loop"

dunno if this is something that can be corrected on your end, or if crazypants will have change his end to fix, but its only really aesthetic, even if albeit seizure inducing. (not really jk, i lol'd when i saw it)

**Comment by CreativeMD** [comment]
I hope it will be fixed soon.

**Comment by plaguewolf** [comment]
cool, thanks. again, its nothing but aesthetic, but nonetheless a compatability thing
