### ISSUE TITLE
[Enhancement] Better custom pickup interaction with modded blocks returning items.

### ISSUE THREAD

**Issue by juraj-hrivnak** [CreativeMD/ItemPhysic#151]
Tested on 1.12.2 version of ItemPhysics-Full
with` CustomPickUp: true`

### The "Issue"
- Some of the moded tile entities (such as **Charger** from **Immersive Engineering** or **Placed Item** from **Plonk**) don't give the item they hold directly to the players' inventory. But instead, the items get dropped on the players' position. And the player must then pick them up from the ground.

- This results in bad QoL when interacting with these tile entities.
### The Idea
Instead of fixing this on the other mods side. I thought about a solution from the ItemPhysics side. _But maybe it's a bad idea._

- **What if ItemPhysics checked for a really small radius around the player when the player right-clicks.**
And then, if there is an item in the radius, it will give the item to the players' inventory. This will probably ensure that the items always end up in players' inventory.

This is a bit of a weird suggestion, I know :D
Also, thank you for such an awesome mod! I've been really enjoying playing with it

**Comment by CreativeMD** [comment]
Thanks for your suggestion!
You can also just sneak to pick up all items around you as normal. I think that makes a lot more sense the right click approach.
