### ISSUE TITLE
[CLIENT - 1.16.5] Mekanism Compat

### ISSUE THREAD

**Issue by KhanhPham05** [CreativeMD/ItemPhysic#152]
Items inside Logistical Transporter when transporting is spinning in crazy

Forge: 36.1.2
Mekanism: 10.0.21.448
ItemPhysics - Full: 1.4.18

**Comment by CreativeMD** [comment]
Reported the issue to Mekanism, let's see if it can be fixed https://github.com/mekanism/Mekanism/issues/7239.

**Comment by CreativeMD** [comment]
I have dropped support for 1.16. This issue will be fixed once Mekanism is released anyway, which means I will close issue.
