### ISSUE TITLE
Villagers Can't pick items up for Breeding

### ISSUE THREAD

**Issue by zndrmn** [CreativeMD/ItemPhysic#153]
Villagers Can't pick items up for Breeding

If you need me to send logs, I can.

**Comment by CreativeMD** [comment]
Which version of ItemPhysic 1.12 or 1.16?

**Comment by zndrmn** [comment]
sorry I kinda posted this in a rush
Minecraft version : 1.16.5
OptiFine version : G8
Forge version : 36.2.0
Mod version : ItemPhysic_v1.4.18_mc1.16.5.jar

Issue : 
Villagers kinda just look at the item that was thrown at them, like bread carrots etc. It looks like they try to pick it up but can't.

I can provide a mod list if needed

**Comment by CreativeMD** [comment]
I tested it myself and could not reproduce this issue. Villagers can pickup items just fine. maybe there is another mod causing this issue (no idea).
