### ISSUE TITLE
Burning BUG

### ISSUE THREAD

**Issue by GabrielToth** [CreativeMD/ItemPhysic#155]
**[BUG] Many items are not burning.**

Minecraft Version: 1.17.1
Forge Version: 37.0.45
Mod version: ItemPhysic_v1.4.18_mc1.17.1.jar
![2021-08-30_02 51 05](https://user-images.githubusercontent.com/60109701/131291880-7e8d9345-f459-4b4a-92a0-f6417d0982f5.png)

> Mod list:
>    Creative Core_v2.2.2_mc1.17.1.jar
>    ItemPhysic_v1.4.18_mc1.17.1.jar

**Comment by CreativeMD** [comment]
That's an feature? You can configure what can burn and what not using the command /cmdconfig -> ItemPhysic.
