### ISSUE TITLE
Item drop physics, /cmdconfig, and mob physics don't work correctly

### ISSUE THREAD

**Issue by Kleptobismaniac** [CreativeMD/ItemPhysic#156]
So basically, the like it says in the title, the item drop physics, /cmdconfigs, and mob physics don't work correctly. 

Firstly, turning item drop physics doesn't do anything. Turning it on and off also doesn't do anything. 

Doing /cmdconfig brings up the cmdconfig page, but there is nothing on it
![2021-10-24_19 51 45](https://user-images.githubusercontent.com/38692995/138619992-198ba95f-8d23-4460-a7ab-5529e6e719e5.png)

Also, mob physics doesn't work correctly. I've tried setting certain mobs to have specific physics but they all only use the blocky physics no matter what.

I know the problem isn't with any other mods because I isolated the mod and creativecore in a separate MultiMC instance, so I really don't know what the problem is.

**Comment by CreativeMD** [comment]
Mob physics is not a feature of this mod, it only changes the behavior of items. Besides that it would be interesting to know which version of ItemPhysic, CreativeCore and Minecraft are you using?

**Comment by Kleptobismaniac** [comment]
> Mob physics is not a feature of this mod, it only changes the behavior of items. Besides that it would be interesting to know which version of ItemPhysic, CreativeCore and Minecraft are you using?

Ok I'm not gonna lie, I'm a dumbass. I got your mod and another mod completely mixed up, my bad bro. I just fixed it and it actually works now. Thanks for makin the mod lol!
