### ISSUE TITLE
Is this ItemPhysics open source?/How can I add ItemPhysics to my minecraft client?

### ISSUE THREAD

**Issue by fenixthexd** [CreativeMD/ItemPhysic#158]
Is this ItemPhysics opensource? If yes, then how can I add it to my minecraft client?

**Comment by CreativeMD** [comment]
Yes, you are on github? You can download it via curseforge: https://www.curseforge.com/minecraft/mc-mods/itemphysic 

You can install it like any other forge mod, maybe watch a tutorial about it.
