### ISSUE TITLE
Problem with item physics

### ISSUE THREAD

**Issue by ThePiggu** [CreativeMD/ItemPhysic#16]
I have a problem with the rotation of items, I can't seem to change it in the config either.
https://www.youtube.com/watch?v=VdULMAbduys

As you can see, the items are spinning really fast, config:

item {
B:customPickup=false
B:customThrow=false
I:despawn=6000
 [range: 0.0 ~ 100.0, default: 1.0]
S:rotateSpeed=1.0
}

**Comment by CreativeMD** [comment]
I'm sorry, i won't fix it for 1.8. I'm working on 1.9, after that i will port the mod back to 1.8.9. I will fix it for those versions.
