### ISSUE TITLE
[Feature Request 1.16.5] Ability to toggle custom pickup on/off

### ISSUE THREAD

**Issue by p1ut0nium-git** [CreativeMD/ItemPhysic#160]
The sneak to pick up all nearby items  feature is alright, but I would rather have a client toggle keybind that turns the custom pickup feature on and off. When off, items would be picked up as normal/vanilla.

Thanks.

**Comment by CreativeMD** [comment]
Sorry, but this is a server wide setting. You can change it using the command /cmdconfig, but it will change it for everyone.
