### ISSUE TITLE
[Feature Request] Compat with Simple Magnets

### ISSUE THREAD

**Issue by p1ut0nium-git** [CreativeMD/ItemPhysic#161]
Is there any way to make this mod work with Simple Magnets? https://www.curseforge.com/minecraft/mc-mods/simple-magnets

Current behavior:

- enable magnet in hot bar
- Mine cobblestone
- Cobblestone drops & is pulled to player’s feet by magnet, but not picked up
- Must right click or sneak to pick up

Desired Behavior:

Dropped items pulled by magnet should go into player inventory without needing to be picked up.

**Comment by CreativeMD** [comment]
Use the command /cmdconfig and go to ItemPhysic -> pickup and disable custom pickup.
