### ISSUE TITLE
Fall physics change.

### ISSUE THREAD

**Issue by PermskyKit** [CreativeMD/ItemPhysic#165]
Hello. There are many mods, in my case it is MrCrayfish's Gun Mod, with non-standard item models. Is it possible to achieve the correct display of objects on the floor by changing the model using resource packs? Is there any guidance on this?

**Comment by CreativeMD** [comment]
It's an issue with 1.12 and it cannot be fixed. It should not be an issue in 1.18. No idea what version you are using, but I doubt I can fix it from my end anyway.
