### ISSUE TITLE
despite disabling whitelist of "burningItems" they do not burn in lava

### ISSUE THREAD

**Issue by v1-valux** [CreativeMD/ItemPhysic#167]
It appears to me, that if I switch "burningItems" whitelist to false (and removing all entries), it doesn't burn any items in lava anymore..

also I tried removing the "swimmingItems" list, because items were floating on lava without burning aswell.
Installed client and server-side. (fabric)

Am I missing an additional setting?

**Comment by CreativeMD** [comment]
It was nothing wrong with the configuration, but instead items did not burn at all. Fixed in the newest version. Thanks for reporting this issue!
