### ISSUE TITLE
Issue with right click to pick up item

### ISSUE THREAD

**Issue by FoxTriforce** [CreativeMD/ItemPhysic#171]
So I have an issue, to pick up items using shift or right clicking them is not working, items on the ground just go into your inventory when near as a vanilla game would, the item's themselves still look and stay on the ground as they would normally, but I can not pick it up as if I were to right click it. Is there any possible way to fix this issue? I have tried deleting the mod and re-installing it from this website 1.4.37 (btw using with RLCraft)

**Comment by CreativeMD** [comment]
Use the command /cmdconfig. Then hit 'ItemPhysic' -> 'pickup' and enable 'customPickup'.

**Comment by FoxTriforce** [comment]
> Use the command /cmdconfig. Then hit 'ItemPhysic' -> 'pickup' and enable 'customPickup'.
Where do I enter this command?

**Comment by CreativeMD** [comment]
In the chat.

**Comment by FoxTriforce** [comment]
> In the chat.

Does this work in survival mode?

**Comment by CreativeMD** [comment]
Yes but only if you have permission to do so.

**Comment by FoxTriforce** [comment]
> Yes but only if you have permission to do so.

Thank you for your time!
