### ISSUE TITLE
1.7.10 workspace required

### ISSUE THREAD

**Issue by Gordon-Frohman** [CreativeMD/ItemPhysic#175]
I'm working on a fix for the 1.7.10 version of the mod for my modpack to stop items from rotating uncontrollably when placed on a Thaumcraft pedestal or a Flaxbeard's Steam Power steam hammer. I think that I've finally found the solution, but unfortunately there's no gradlew.bat in the 1.7.10 branch, so I'm unable to compile and test it. I am pretty much a novice in modding, so I'm unable to properly setup a workspace myself. So I guess asking you is the only option left for me.
I know it's been a while since you've uploaded the 1.7.10 version of the mod, but maybe you can provide me a workspace to properly compile the source code, or at least give me a few tips on how to do it myself, please?

**Comment by CreativeMD** [comment]
This tutorial is for 1.12, but it should be the exact same for 1.7.10: https://www.youtube.com/watch?v=7Ahshi_QjM4
