### ISSUE TITLE
incompatibility with lychee tweaker

### ISSUE THREAD

**Issue by 800020h** [CreativeMD/ItemPhysic#179]
versions:
minecraft 1.19.2
Fabric Loader 0.14.19 + Fabric API 0.76.0+1.19.2
Lychee-1.19.2-fabric-3.10.1
ItemPhysic_FABRIC_v1.6.6_mc1.19.2
CreativeCore_FABRIC_v2.9.3_mc1.19.2

log:
replaced with redacted copy
https://gist.github.com/800020h/0ea5cf9d1ad1dfed76243a5b56f82809

see also:
https://github.com/Snownee/Lychee/issues/44

crash on launch with lychee
something to do with item entities

**Comment by CreativeMD** [comment]
Hey, thanks for reporting this issue. Unfortunately I do not support 1.19.2 anymore. I have fixed the issue for 1.19.4 however. So once lychee tweaker will update the issue will be fixed.
