### ISSUE TITLE
Items...

### ISSUE THREAD

**Issue by GamerForYears** [CreativeMD/ItemPhysic#18]
So, When i downloaded the mod, I threw a bunch of items and blocks and the items weren't on the ground, they were just floating in mid air.Please please please fix (oh and fix for version 1.7.10 plz!)Cause i use 1.7.10 forge Thanks!

**Comment by GamerForYears** [comment]
Please fix and i will love this 1.7.10 and older versions mod! :yellow_heart:

**Comment by CreativeMD** [comment]
Erhm, sorry but your issue report is somehow confusing. It would be nice if you could provide some screenshots are something like that. Sadly, i'm not able to get what you are trying to say, neither do i know whether you use the Lite or the Full version.

My mod does support 1.7.10 and it also does support 1.6.x.

**Comment by GamerForYears** [comment]
Im sorry what im trying to say is that i installed Item physics 1.1.5 lite and i put it in the mods folder and i tryed to throw items and this happened  http://imgur.com/NXWf6US

**Comment by CreativeMD** [comment]
Enable fancy graphics

**Comment by GamerForYears** [comment]
Thanks for letting me know Youre the best :)
