### ISSUE TITLE
On server can't pick up dropped items from players

### ISSUE THREAD

**Issue by 19-creator** [CreativeMD/ItemPhysic#188]
Items dropped from other players on a server you can't pickup only can pick up items dropped by yourself.
Mod version: ItemPhysic_FORGE_v1.6.15_mc1.20.1

**Comment by CreativeMD** [comment]
Are you sure that this is the case? If custom pickup is enabled you can only pickup items using right click or sneaking while standing close to it.

**Comment by 19-creator** [comment]
> Are you sure that this is the case? If custom pickup is enabled you can only pickup items using right click or sneaking while standing close to it.

Yes I am aware of that setting and I use it however I have the crouch off because I like that off. Yeah though, players right clicking items another player drops on the server doesn't allow them. I think it has something to do with the pickup delay mechanic where the player who drops the item will pick up the item before the person they are giving it to will.

**Comment by CreativeMD** [comment]
It's fixed. Thanks for reporting this issue. Crazy how long it must have existed. Newest version should be available in a few minutes.
