### ISSUE TITLE
Ars Nouveau Rendering

### ISSUE THREAD

**Issue by lukenator115** [CreativeMD/ItemPhysic#190]
This mod applies to items being used by the ars nouveau mod, including in the enchanting apparatus and similar in-world item display blocks. This mod applying to the items makes them look strange and sometimes clip through the blocks. Would it be possible to add compatibility?

**Comment by CreativeMD** [comment]
Sorry, but that is something I will not do on my end. They can disable the special rendering for their items by using added a method to their ItemEntities, not sure if that is possible in their case. But I cannot go through all the mods and disable certain items, that would not be good performance wise.
