### ISSUE TITLE
Other players can not pick up items with the right button in multiplayer.

### ISSUE THREAD

**Issue by MOS12546** [CreativeMD/ItemPhysic#193]
I recently noticed a bug when I invited my friends to play with me. They were unable to pick up items on the ground, even though I had turned on the "customPickup" option. However, I discovered that the "pickupWhenSneaking" feature does work. To clarify, every player can actually pick up items by pressing the shift key. It would be great if you could help fix this issue. Thank you!
Game version: _1.18.2 forge_

**Comment by CreativeMD** [comment]
That is weird. Unfortunately I do not support 1.18.2 anymore. I know this was an issue at some point, but I thought it was fixed for 1.18.2, but seems like it is not. Sorry for the trouble. I recommend to update if possible.

**Comment by MOS12546** [comment]
Alright, don't mind.
