### ISSUE TITLE
[Question & Suggestions] Throwing power

### ISSUE THREAD

**Issue by BioTechproject27** [CreativeMD/ItemPhysic#194]
Hey, I wanted to ask wether it's possible to configure the throwing power & accuracy? I was not able to find anything in the configs (as of 1.7.0).

Also (probably a bug): The hand stops swinging when changing POV (with `F5`) while still pressing `Q` to charge the throw.

As for suggestions:
It would be good to have a different kind of animation when charging the throw? It looks more like the character is punching something, especially in first person.
Also it would be nice if the item tooltip would honor item name colors and other formatting (e.g. enchanted golden apple should be purple; custom named items, etc).
Also also it would be nice if one could have the option move the tooltip somewhat (e.g. in x & y direction as well as different anchor points), as it's currently directly in the crosshair.

**Comment by CreativeMD** [comment]
Sorry, but at the moment I do not have the time to get into the animation stuff. Adding a special throw animation is quite difficult. The current one is an easy solution and yes it has it's limits. I have fixed the missing name colors. I also add an option to define an offset of the tooltip.

**Comment by BioTechproject27** [comment]
Ah I see, well, the animation could be something for the future.
> Hey, I wanted to ask wether it's possible to configure the throwing power & accuracy? I was not able to find anything in the configs (as of 1.7.0).

Btw what about this? Also, not just power (standard 1 through 6) & accuracy, but also time between power increases (e.g. being able to set it to 40 ticks)

**Comment by BioTechproject27** [comment]
Or having to press a modifier key to increase value. Just something that allows for greater control

**Comment by CreativeMD** [comment]
Sorry I wanted to respond earlier, but kinda forgot. Would a configuration for the throw power limit and how long the charging needs be enough?

**Comment by BioTechproject27** [comment]
i think so, the config should be server side probably/server & client synced

**Comment by CreativeMD** [comment]
Added it in the newest version. Thanks for taking the time to help out. Hope you like the new changes.
