### ISSUE TITLE
Incompatible with Wither Storm.

### ISSUE THREAD

**Issue by xelotex** [CreativeMD/ItemPhysic#195]
Crash on startup when trying to load the game with item physic and Wither Storm installed. MC 1.20.1 forge.

I'll leave the log files:

[debug.log](https://github.com/CreativeMD/ItemPhysic/files/15141122/debug.log)
[latest.log](https://github.com/CreativeMD/ItemPhysic/files/15141123/latest.log)

**Comment by CreativeMD** [comment]
Can you report this to the Wither Storm mod and report it here? I will join the conversation and see if we can figure out a solution together.

**Comment by xelotex** [comment]
> Can you report this to the Wither Storm mod and report it here? I will join the conversation and see if we can figure out a solution together.

I actually tried first to report the issue there but it didn't let me submit it. I cant even upload the log files there. Can you try and see if it lets you report it there?

**Comment by xelotex** [comment]
This has been fixed in WitherStorm V4.1

**Comment by CreativeMD** [comment]
Very nice!
