### ISSUE TITLE
Guns dropping badly

### ISSUE THREAD

**Issue by iulikjulik** [CreativeMD/ItemPhysic#199]
Hi, the guns from MrCrayfish are rotated on half under ground when ItemPhysic used, if i could set somehow vanillaRendering only for a list of item or change the angle, it would fix the issue, but i am too dumb and don't know java to be able to do this

**Comment by CreativeMD** [comment]
Other mods can make their items use the vanilla rendering quite easily. All they need to do is to set the field `skipPhysicRenderer` in `ItemEntity` to true. There is also an option to change that behavior using the config. Use the command /cmdclientconfig -> itemphysic -> rendering -> vanillaRendered. There you can add items which rendering behavior should revert back to normal.
