### ISSUE TITLE
customPickup does not pick up the item

### ISSUE THREAD

**Issue by avsane** [CreativeMD/ItemPhysic#202]
https://github.com/user-attachments/assets/5680d07c-856f-4107-9147-a18f026ddf45

CustomPickup does not pick up the item, but it does make the item disappear. PickupWhenSneaking is the only way to pick it up.

- ItemPhysic v1.7.2
- CreativeCore v2.12.5
- NeoForge v21.0.139-beta

**Comment by CreativeMD** [comment]
Normally it does work. You are in singleplayer right? Any configurations you have changed? Normally it does work.

**Comment by CreativeMD** [comment]
I will close this due to inactivity. If the issue persists please respond here.
