### ISSUE TITLE
The configuration gets corrupted when I switch to an old version of the mod and it interferes  

### ISSUE THREAD

**Issue by FilipKompaniets3** [CreativeMD/ItemPhysic#206]
After using the mod on newer versions, when I update to 1.12.2 with the mod, my world collapses because the config gets corrupted when used on 1.12.2. I don't want to delete the config every time I update from a later version to 1.12.2. 
I like your mod and I would be very happy if it didn't have this problem that makes me not want to use it, so I am forced to look for a decent replacement mod until the problem is solved. (the message is written through google translate, so it may not be clear).

I am using versions 1.20.1 and 1.12.2

**Comment by FilipKompaniets3** [comment]
> Після використання мода в новіших версіях, коли я оновлюся до 1.12.2 з модом, мій світ руйнується, оскільки конфігурація пошкоджується під час використання на 1.12.2. Я не хочу видаляти конфігурацію кожного разу, коли оновлюю пізнішу версію до 1.12.2. Мені подобається ваш мод, і я був би дуже радий, якби в ньому не було цієї проблеми, через яку я не хочу його використовувати, тому я змушений шукати гідний мод на заміну, доки проблема не буде вирішена. (повідомлення написано через гугл транслейт, тому може бути незрозумілим).
> 
> Я використовую версії 1.20.1 і 1.12.2, latest versions of ItemPhysic and CreativeCore mods

**Comment by CreativeMD** [comment]
Responded to you over on curseforge. I recommend to use a launcher which allows you to not having to switch between these two versions but have to separate minecraft instances. One solution could be MultiMC.

**Comment by FilipKompaniets3** [comment]
I don't have the opportunity to use paid launchers(

**Comment by CreativeMD** [comment]
MultiMc is free.

**Comment by FilipKompaniets3** [comment]
> MultiMc безкоштовний.

Really?! I remember that to use it you needed a paid Minecraft license. I'll check later.
