### ISSUE TITLE
Permission to distribute a fork

### ISSUE THREAD

**Issue by kotmatross28729** [CreativeMD/ItemPhysic#207]
Hello, I am reaching out to inquire about the possibility of uploading my forked version of ItemPhysic, specifically tailored for Minecraft 1.7.10, to CurseForge and Modrinth.

As a forker, I typically focus on maintaining abandoned or MIT-licensed mods, but I am unsure about the licensing terms and conditions of this particular mod.

For reference, I have made the fork available on GitHub at the following link: https://github.com/kotmatross28729/ItemPhysic.
 I would appreciate any guidance or clarification on the matter, as I strive to ensure compliance with the original author's intentions and licensing agreements.

**Comment by CreativeMD** [comment]
As long as you do this for versions in 1.7.10 (or older versions I do not support anymore) I am totally fine. Sounds like a cool project. I would also be done to post a link to your project page on Curseforge and Modrinth. Also very kind of you to ask!
