### ISSUE TITLE
[Suggestion] Whitelist/Blacklist for Throwable Items

### ISSUE THREAD

**Issue by joebig22** [CreativeMD/ItemPhysic#208]
Would be cool if there was a whitelist or blacklist to what could be thrown

Use Case Example:

In the case there is a glowstick recipe in a modpack
The glowstick would always be more expensive than the torch (since coal and wood is kinda easy to get), so the players would naturally prefer to craft torches, since both of them can be thrown and the only difference is their model
By adding torches to a throwable blacklist and allowing glowsticks to be thrown, the modpack creator could give the glowsticks a reason to be crafted (a light emitting item that can be thrown) (while the torch cant) (be thrown)

**Comment by CreativeMD** [comment]
You mean throwing far? Would be weird if you could not drop certain items.
