### ISSUE TITLE
customPickup doesn't pick up items

### ISSUE THREAD

**Issue by gaysarys** [CreativeMD/ItemPhysic#209]
"customPickup" right-clicking on an item does not pick up, but makes it invisible, but if "pickupWhenSneaking" is enabled, using this on place where the item disappeared will pick up item. Also, when re-joining to the world, the disappeared items become visible again. There are no errors in log.
Tested on survival/creative, singleplayer,
- minecraft v1.21.1
- neoforge v21.1.72
Mod list:
- CreativeCore NEOFORGE v2.12.17
- ItemPhysic NEOFORGE v1.8.1
Config (nothing changed in config except this):
"customPickup": true,
"pickupWhenSneaking": true,
"pickupNormally": false

**Comment by gaysarys** [comment]
The bug seems to be fixed in the latest update:
CreativeCore 2.12.19
ItemPhysic 1.8.2

**Comment by mttic** [comment]
I'm having the same issue right now on the latest version of both mods for Fabric 1.21.1

**Comment by CreativeMD** [comment]
Alright, I forgot to upload the fix for Fabric as well. The newest version fixes it. Sorry for the trouble.
