### ISSUE TITLE
Disconnect from server when throwing an item.

### ISSUE THREAD

**Issue by InsaneJ** [CreativeMD/ItemPhysic#21]
When throwing an item I get disconnected from the server. After the disconnect I can re-connect right away. 

Minecraft 1.10.2
Forge 12.18.1.2089
ItemPhysic Full 1.3.3 mc1.10.2 and CreativeCore v1.6.3 mc1.10.2

Disconnect error on server: http://paste2.org/s7GJpZNC
Full server log: http://paste2.org/7C3ptaBc
Client log: http://paste2.org/cvXf8FK8

**Comment by CreativeMD** [comment]
Please try to use another Forge version, i suggest to try it using '12.18.1.2076'. It seems to be an forge issue.

**Comment by TheRealDadbeard** [comment]
Same issue here. It works without an issue on local singleplayer. Getting the same error as above. Lite version works fine!

http://paste2.org/yUbbgL9H

**Comment by CreativeMD** [comment]
Could you try out if the newest version of CreativeCore fixes this issue?
https://www.dropbox.com/s/y92vtydd1q6j078/CreativeCore%20v1.6.11%20mc1.10.2.jar?dl=1

**Comment by TheRealDadbeard** [comment]
Works now. No crashes at all. Throwing works and pickups too.

**Comment by CreativeMD** [comment]
Nice, i have released this new CreativeCore version, so there shouldn't be a problem anymore. Thanks for helping out.
