### ISSUE TITLE
Mod causes game to crash on start-up

### ISSUE THREAD

**Issue by Nevrai** [CreativeMD/ItemPhysic#210]
**Crash report**: https://pastebin.com/7J6SvSy7

### Versions
* **Raspberry Flavoured**: 2.2 Pre-Release 8
* **Minecraft**: 1.19.2
* **Forge**: 43.3.7
* **ItemPhysic Full**: 1.6.7
* **CreativeCore**: 2.9.4

**Comment by CreativeMD** [comment]
Update CreativeCore.
