### ISSUE TITLE
[Bug] Massive lag issue

### ISSUE THREAD

**Issue by Deepfriedyag** [CreativeMD/ItemPhysic#211]
I mentioned it in CreativeCore issues but it is probably ItemPhysic that causes it. See https://github.com/CreativeMD/CreativeCore/issues/263

**Comment by CreativeMD** [comment]
Yep, it is indeed ItemPhysic that causes this. Most likely this can happen if you have countless items laying in the floor. Normally it should not effect performance that much. Also the screenshot seems a bit weird to me, because it cannot be that this uses 100% of the CPU performance.

**Comment by CreativeMD** [comment]
I will close this issue for now. I need more information to do something with it. Maybe send me the lagging world so I can do some testing myself.
