### ISSUE TITLE
[BUG] Startup crash with Doggy Talents.

### ISSUE THREAD

**Issue by Deepfriedyag** [CreativeMD/ItemPhysic#212]
I checked the previous issues about this and it said the bug was fixed by the doggy talents author but I still get the crash when both of these mods are on the latest version in 1.12.2 This crash only happens when using the lite version of ItemPhysic.

It is lengthy but here is the log: 
[latest.log.txt](https://github.com/user-attachments/files/17608619/latest.log.txt)

**Comment by CreativeMD** [comment]
Please use ItemPhysic and not ItemPhysic Lite. That should fix the issue.
