### ISSUE TITLE
Having liteloader installed makes the itemdrop key weird

### ISSUE THREAD

**Issue by TheRealDadbeard** [CreativeMD/ItemPhysic#22]
So after installing liteloader when dropping something it's always 2 items per drop. Holding doesn't seem to work too. Starting with only forge fixes it. I'm a little bit confused why...

[fml-client-latest.txt](https://github.com/CreativeMD/ItemPhysic/files/594652/fml-client-latest.txt)
[latest.txt](https://github.com/CreativeMD/ItemPhysic/files/594651/latest.txt)

**Comment by CreativeMD** [comment]
I have contacted the author of LiteLoader, maybe we can fix the bug:
http://develop.liteloader.com/liteloader/LiteLoader/issues/16

**Comment by TheRealDadbeard** [comment]
Thank you very much!

**Comment by CreativeMD** [comment]
I'm really sorry, but fixing this bug will take more time and i'm currently busy updating LittleTiles, at least 2 weeks :(

**Comment by TheRealDadbeard** [comment]
Not a problem at all. Take your time bro! Everything's good ;) LTiles is a much bigger mod than this. :D

**Comment by CreativeMD** [comment]
It is fixed, please update to the newest CreativeCore version
