### ISSUE TITLE
Thaumcraft Issues - Items placed on Pedestals spin, spin, spin.

### ISSUE THREAD

**Issue by Bushcrafts** [CreativeMD/ItemPhysic#23]
Placing items on the pedestals causes them to spin violently. They also are not placed upright, they just lay down flat and just spin, spin, spin.

It looks like this was mentioned and acknowledged last year. Are there any updates to this?

https://github.com/CreativeMD/ItemPhysic/issues/9

Oh and before you ask, this was Thaumcraft's reply, albeit not very informative lol!

"This is not something that needs to be fixed on my side."

Thanks!

**Comment by CreativeMD** [comment]
Which version are you using? Some time ago (mid 2015) i have talked to @Azanor and showed him a potential fix, but he hasn't found any time to do it. I have no tested it but i think it's fixed in 1.8+, don't expect any fixes for 1.7.10 anymore, sorry :(.
