### ISSUE TITLE
Crashed When Pick My Torch Up Back From Ground

### ISSUE THREAD

**Issue by ghost** [CreativeMD/ItemPhysic#25]
it's really so sad :( i just pressed Q with torch, then tried to pick it up back but crashed :(
using game 1.11.2, forge 2226. using full version of the mod. here is the crash report:
[crash-2017-02-02_19.50.04-client.txt](https://github.com/CreativeMD/ItemPhysic/files/748397/crash-2017-02-02_19.50.04-client.txt)
please help :( thanks.

**Comment by ghost** [comment]
it works fine with lite one, but the FULL one.

**Comment by CreativeMD** [comment]
Should be fixed in the newest version. Just reopen the issue if it does still occur.
