### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [CreativeMD/ItemPhysic#28]
Please help :( it crashed in game, here is the crash report:
[crash-2017-02-16_13.05.09-client.txt](https://github.com/CreativeMD/ItemPhysic/files/779749/crash-2017-02-16_13.05.09-client.txt)
it has crashed when putting the microwave of crayfish's furniture mod
And when i try to load my world, it crashes again :
[crash-2017-02-16_13.17.53-client.txt](https://github.com/CreativeMD/ItemPhysic/files/779750/crash-2017-02-16_13.17.53-client.txt)

**Comment by CreativeMD** [comment]
Does this version fix it?
https://www.dropbox.com/s/36ca04zoumh0ov6/ItemPhysic%20Full%201.3.11%20mc1.11.2.jar?dl=1

**Comment by ghost** [comment]
YES! Thank you.

**Comment by CreativeMD** [comment]
New version is release. Thanks for reporting this issue.

**Comment by ghost** [comment]
yeah i installed it. thanks
