### ISSUE TITLE
Compatibility With Iron Chests Mod

### ISSUE THREAD

**Issue by ghost** [CreativeMD/ItemPhysic#32]
normally, items are shown in the middle of the crystal chest in iron chests mod (they are turning their around slowly) but when i install ItemPhysic, they are turning all around fast like crazy. please fix this :D thanks.

**Comment by ghost** [comment]
https://minecraft.curseforge.com/projects/iron-chests?gameCategorySlug=mc-mods&projectID=228756

**Comment by CreativeMD** [comment]
This should fix both of your issue:
https://www.dropbox.com/s/xm5dumq5cfv2a8g/ItemPhysic%20Full%201.4.2%20mc1.11.2.jar?dl=1

**Comment by ghost** [comment]
okay let me test it <3

**Comment by ghost** [comment]
yes! it works!! thank you so much!!!! we love you

**Comment by CreativeMD** [comment]
Thanks for reporting those issue.
