### ISSUE TITLE
MC 1.10.2 Wood item not floating when on server.

### ISSUE THREAD

**Issue by VirtualGaming1** [CreativeMD/ItemPhysic#35]
I did a little test (Well want to show off to a friend) and i throw a wood slab and sink to the bottom and just a wood block. sink. just want to let you know about this and seem like im the first one also.

**Comment by VirtualGaming1** [comment]
NVM just realize that its missing core mod opps

**Comment by VirtualGaming1** [comment]
ok dose know seem to be working still even with the core mod in the server

**Comment by CreativeMD** [comment]
I think you are using Lite, but in order to have water physics you would have to use Full. Lite is client side only. Full has to be installed on the server as well together with CreativeCore.

**Comment by VirtualGaming1** [comment]
Both of the server and client have full (ItemPhysic Full 1.3.10 mc1.10.2.jar) and the latest 1.10.2 CreativeCore.

do you want me put in the list of mods that I have in my pack?

**Comment by CreativeMD** [comment]
Does ordinary wood float? If not yes and i will need the forge version as well.

**Comment by VirtualGaming1** [comment]
Both Client and Server Forge Version: 12.18.3.2281


Advanced Chimneys 1.2.3.0
Animania 1.0.4.6
Auto Sapling 1.3.3
BiblioCraft 2.2.1
Binocular 1.2
Chameleon 2.2.2
clipboard 1.1.1
CodeChicken Core 1.8+ 2.4.1.102-Universal
CodeChicken Lib 1.8+ 2.5.7.241-universal
CoFH Core 4.1.1.156-Universal
Compackt Solars 5.0.8.331-universal
CompatLayer 0.2.5
CoroUtil 1.1.14
Creative Core 1.6.26
Custom Mob Spawner 3.10.1
Davincis Vessels 0006-full
DtCyano's Lootable Bodies 2.2.0
Ender IO 3.1.180
EnderCore 0.4.1.65-beta
(Client Only) EnhancedVisuals 1.0.11
Farseek 2.1
Forestry 5.2.17.374
Forge MultiPart CBE 2.0.0.31
ForgeEndertech 1.2.2.0-Build.0021
(Client Only) Fullscreen Windowed (Borderless) for Minecraft   1.5.0
Hide Names 1.3
iChunUtil 6.3.0
Immersive Engineering 0.10-57
Industrial Craft 2.6.188-ex110
Industrial Wires 1.3-8
Inventory Tweaks 1.61-58
iTank 1.1.0
ItemPhysic (Yours) Full 1.3.10
Just Enough Item 3.14.7.417
LittleTiles 1.4.3
Mantle 1.1.5
MapWriter2 2.6.19
McjtyLib 2.3.11
MCMultiPart 1.4.0-universal
Minecraft Comes Alive 5.2.3
Minecraft Flight Simulator 7.1.2
Mo' Creatures 10.0.6
Mob Amputation 6.0.0
MovingWorld 0007-full
mp3spi 1.9.5-1
MrCrayfish's Furniture Mod 4.1.2
MrThpCore 2.0.0.14-universal
Neat 1.3-12
Not Enough Item 1.8.+ 2.1.3.207-Universal
OpenComputer 1.6.2.7
OpenFM 0.1.0.22
OpenPrinter 0.1.0.5
Packing Tape 0.6.0
Pam's HarvestCraft 1.10.2h
Pam's Simple Recipes 1.10.2a
Parachute Mod 1.5.2-416
(Client Only) Picture-in-Picture (PiP) 6.0.0
Platforms 1.10.0
Project Red - Base 4.8.1.25-Base
Project Red - Integration 4.8.1.25-integration
Project Red - Lighting 4.8.1.25-lighting
Project Red - Mechanical 4.8.1.25-mechanical
Project Red - 4.8.1.25-world
RadixCore 2.1.3-universal
RailCraft 10.0.1
(Client Only) Real First-Person Render 8.1.1
Realistic Torches 1.6.4
RFTools 1.1x-5.92
RFTools Control 1.1x-1.6.6
Rough Tweaks 0.1
Shadowfacts' Forgelin 1.4.1
ShadowMC 3.6.1
Simulated Nights 1.1.2
Sleeping Bag 1.4.0
(Client Only) Sound Filters
Steve's Factory Manager Reborn 1.0.12
Steves Carts Reborn 2.1.4.83
Storage Drawers 3.7.1
Streams 0.3
Super Circuit Maker 1.0.4
Thermal Expansion 5.0.4.90
Thermal Foundation 2.0.5.81
Tinkers Construct  2.6.3
Vic's Modern Warfare Mod 1.9
vorbisspi 1.0.3-1
Waila 1.7.0-B3
Waila Harvestability 1.1.9
Wawla 2.3.2.215
Wearable Backpacks 1.6.0
Weather, Storms & Tornadoes (Local Weather) 2.4.9
Wireless Redstone CBE 2.0.0.18-universal
Zombie Awareness 1.11.6

**Comment by VirtualGaming1** [comment]
Update: I notice that it works on SP but no the MP plus i notice issue with the EnhancedVisuals same way too

**Comment by VirtualGaming1** [comment]
@CreativeMD what version of Forge API are you using?

**Comment by VirtualGaming1** [comment]
Im wondering if that its not loading fully because forge is detecting a core-mod inside it.

**Comment by CreativeMD** [comment]
Could you update to the newest versions of CreativeCore, LittleTiles (link below) and ItemPhysics?

https://www.dropbox.com/s/v5debkw26uajnf1/LittleTiles%20v1.4.8%20mc1.11.2.jar?dl=1

EDIT
Oh damn forgot you were using 1.10.2 :(

**Comment by VirtualGaming1** [comment]
i have all of those mods to latest version. and just want to let you know that i am using the Twitch app (use to call Curse app) to make my modpack.

**Comment by CreativeMD** [comment]
Could you new update to the newest version and test if it's fixed?

https://www.dropbox.com/s/fmzo9zia7s93l2y/ItemPhysic%20Full%201.4.2%20mc1.10.2.jar?dl=1

**Comment by VirtualGaming1** [comment]
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: com/creativemd/creativecore/common/utils/sorting/SortingList

**Comment by CreativeMD** [comment]
You forgot to update CreativeCore and LittleTiles

**Comment by VirtualGaming1** [comment]
oh did not realize they have an update thanks for letting me know :p

**Comment by VirtualGaming1** [comment]
i did a test with wood planks and it still sinks

**Comment by VirtualGaming1** [comment]
but one thing i could say is that the pick up works right now on the servers

**Comment by VirtualGaming1** [comment]
@CreativeMD just want to let you know the next time i would be able to do another test is around after 9pm central Time

**Comment by CreativeMD** [comment]
It's fixed. Please redownload the newest CreativeCore and the newest ItemPhysic version (both should be available in a few minutes. Thanks for reporting.
