### ISSUE TITLE
Item Physics CustomPickup config

### ISSUE THREAD

**Issue by Cazadorsniper** [CreativeMD/ItemPhysic#36]
After some days, I finally found that custom pickup was causing fps to drop the further a person travel from spawn on both multiplayer and singleplayer. 

Turn it on then move away from spawn about 300,000 blocks (recommend JourneyMap) and fps will drop to 36 or lower. Turn it back off and fps goes back to normal.

**Comment by CreativeMD** [comment]
Thanks for reporting this issue. It was rather easy to fix. Update 1.4.3 will be available soon.
