### ISSUE TITLE
compatibility bug

### ISSUE THREAD

**Issue by ghost** [CreativeMD/ItemPhysic#37]
![bugg](https://cloud.githubusercontent.com/assets/24831406/25530972/d13e8d90-2c30-11e7-85fa-2ea4bfe75158.png)
thanks.....
forge 2285

**Comment by ghost** [comment]
hey, don't abandon this bug :D

**Comment by CreativeMD** [comment]
I have not forgot it, but this is more complicated to fix.

**Comment by ghost** [comment]
hmm :l okay, get luck with

**Comment by CreativeMD** [comment]
Looks like it's fixed (even the issue we had previously):
![](http://i.imgur.com/u3hBeoI.png)

https://www.dropbox.com/s/rmbqty9q2whe03n/ItemPhysic%20Full%201.4.4%20mc1.11.2.jar?dl=1

**Comment by ghost** [comment]
oh! thanks a lot!!

**Comment by CreativeMD** [comment]
Thanks for reporting this issue, hope it is fixed forever.
