### ISSUE TITLE
Amazing Bug/Crash

### ISSUE THREAD

**Issue by ghost** [CreativeMD/ItemPhysic#39]
hello, please try my [modpack](https://www.technicpack.net/modpack/magenjia.1010676) and try to drop any item in the world. if you have no time, here is the latest logs:
[2017-05-14-3.log.txt](https://github.com/CreativeMD/ItemPhysic/files/999709/2017-05-14-3.log.txt)

problem: when i try to drop any item by pressing Q, my server(internal server, single player world) stops running and the game returns to the multiplayer tab(my world closes instantly or just freezes)
it doesn't happen if i drop item in inventory gui (dropping on space)
and it doesn't happens without Itemphysic.
it wasn't happening before, i just updated some mods and optifine, forge.
please help, thanks..

**Comment by CreativeMD** [comment]
Could you send me the crash report of the server (it looks like you send me the crash log of the client)?

**Comment by ghost** [comment]
There is no crash report, because i tried it in singleplayer. I created a world, pressed Q with an item, then it said shutting down... and game returned to the multiplayer tab. I checked the folder but couldn't find any crash report, because game was alive. Thanks...

**Comment by CreativeMD** [comment]
This error is weird, but it looks like `santa.ping` seems to be the issue here. Could you turn of fallSounds of ItemPhysic (in the config) and see if it is fixed?

**Comment by ghost** [comment]
let me try.

**Comment by ghost** [comment]
uhm no, it didn't work.

**Comment by ghost** [comment]
i deleted the ping mod also, still crashes (game freeze)

**Comment by ghost** [comment]
any other idea? :(

**Comment by ghost** [comment]
still waiting for help :( we can't drop any item :(

**Comment by CreativeMD** [comment]
Sorry, i have been rather busy. Could you try to find out which mod is conflicting? I don't know how many mods you have installed, but it would really really help, if you could go through each mod and test if it still occurs or not.

**Comment by ghost** [comment]
okay i'm making tests...

**Comment by ghost** [comment]
but i don't understand why it doesn't crash, just freezes...

**Comment by ghost** [comment]
hey, it's fixed when i delete IGCM. 
test 1: Creative Core + ItemPhysic = works fine
test 2: Creative Core + ItemPhysic + IGCM = freeze/crash
used forge 2296, CC 1.7.3, IGCM 1.1.4, ItemPhysic 1.4.4
please help...

**Comment by ghost** [comment]
oh wait, it fixed when i delete configs too. hmm.. let me test it more
edit: it's not happening when i delete my IGCM .nbt data file (in config) which has my custom recipes, options etc. what should i do? you want me upload my IGCM config files?

**Comment by ghost** [comment]
here is my IGCM config file. if you put this into config folder and install CreativeCore + ItemPhysic + IGCM, your game will freeze when you drop any item by pressing Q. i don't know what is the problem.
https://drive.google.com/open?id=0B6b0yPfoStOGb1NZdkRZbjEyZkk

**Comment by ghost** [comment]
help please...

**Comment by CreativeMD** [comment]
Sorry, still rather busy, i will try to take a look at it today.

**Comment by ghost** [comment]
thanks :( hope it will be fixed. we can't drop any item :( it's terrible...

**Comment by ghost** [comment]
well, i remade all recipes in igcm from zero.
