### ISSUE TITLE
Curseforge files.

### ISSUE THREAD

**Issue by Claycorp** [CreativeMD/ItemPhysic#40]
Currently you are uploading both files separately. Please stop doing this as it will unintentionally switch peoples versions between full and lite as CurseForge doesn't know they are totally separate things. Either make a new project or set them as children files of the parent. Thanks.

**Comment by CreativeMD** [comment]
I feel you ... but i don't see any other solution. I don't want to separate those projects, since people will only know one of them and forget about the other one. I can't group the downloads either, since the Lite and the Full versions are not really on the same version "level".

**Comment by Claycorp** [comment]
Well the only other option is to merge the mod into one. Make it where if the mod is on the client but not the server you can still connect but it will work as the lite version. You could also add a config to make it lite only.

Splitting it up would be easiest and lots of other devs have done it. They don't have issues with people not finding the mods, Juts link them to each other in a giant font size at the top and people will find them.

**Comment by CreativeMD** [comment]
I don't want to merge those two versions, since some people don't like the physics, but only enjoy the animation.
Yeah, maybe a giant header would do it, i will think about that.

**Comment by CreativeMD** [comment]
I created a new project for ItemPhysic Lite, but unfortunately curseforge does not anything with it. I hope it will be approved eventually. Anyway thanks for you suggestion i will close this issue now.
