### ISSUE TITLE
Config for igniting wasn't added to 1.10.2 version

### ISSUE THREAD

**Issue by thephoenixlodge** [CreativeMD/ItemPhysic#41]
Despite the [changelog for 1.4.5](https://minecraft.curseforge.com/projects/itemphysic/files/2427475) for 1.10.2 claiming to have added a config for the igniting, looking at the relevant part of the source, the commit was only for the 1.11.2 version of the mod (https://github.com/CreativeMD/ItemPhysic/commit/6b3fe8d0b9e0ec1478a48ca342f8b84299ea417e)
and there is no igniting items part to the config defined in [ItemDummyContainer in the 1.10.2 branch](https://github.com/CreativeMD/ItemPhysic/blob/1.10.2/src/main/java/com/creativemd/itemphysic/ItemDummyContainer.java#L90)
This is reinforced by a freshly generated config file lacking the config option too.

**Comment by CreativeMD** [comment]
Oh right, my bad. The new version should be available in a second.
