### ISSUE TITLE
Crashed After 3 seconds of creating world

### ISSUE THREAD

**Issue by ghost** [CreativeMD/ItemPhysic#42]
[crash-2017-07-02_15.13.01-client.txt](https://github.com/CreativeMD/ItemPhysic/files/1117778/crash-2017-07-02_15.13.01-client.txt)
i have no idea, i was in a jungle

**Comment by CDAGaming** [comment]
For me it crashed when someone in my server broke a block (On 1.12)

**Comment by CreativeMD** [comment]
Forge is changing a lot. If you use the newer versions of forge this crash will occur. I will update ItemPhysic this week.

**Comment by CDAGaming** [comment]
Thank you very much, as oddly enough OPTIFINE is also crashing(Wonder what Forge changed to have Optifine and this crash, but glad this mod will be fixed :) )

**Comment by CreativeMD** [comment]
Could you try out the new version of ItemPhysic and CreativeCore and see if it is fixed?

**Comment by ghost** [comment]
(_if me asked, i deleted all my modpack files and everything, now coding a new mod_)

**Comment by CreativeMD** [comment]
Ok, i guess it is fixed now, if not just reopen this issue.

**Comment by CDAGaming** [comment]
Yea, for me i think it's fixed, as optifine is running normal now
