### ISSUE TITLE
[1.12] When right clicking on item, a clone of the same item is created

### ISSUE THREAD

**Issue by NovaViper** [CreativeMD/ItemPhysic#43]
Uh.. I just updated to ItemPhysics Full 1.4.6 for 1.12 and I noticed a rather strange bug. Whenever I right click on an item on the ground (tested in both Creative and Survival), I get the same item twice in my inventory

**Comment by CreativeMD** [comment]
It is fixed in 1.4.7. Thanks for reporting.

**Comment by NovaViper** [comment]
Np!
