### ISSUE TITLE
Crash on 1.12.1

### ISSUE THREAD

**Issue by ChloeDawn** [CreativeMD/ItemPhysic#45]
Client crashes to desktop during startup.

**Mod version:** [Full 1.4.7](https://minecraft.curseforge.com/projects/itemphysic/files/2449032)
**Forge version:** [1.12.1-14.22.0.2459](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.1-14.22.0.2459/forge-1.12.1-14.22.0.2459-changelog.txt)

**Crash information:** [fml-client-latest.log#L735-L777](https://gist.github.com/InsomniaKitten/4c7db57a9c8f9610489e16b873e3f7ff#file-fml-client-latest-log-L735-L777)

**Comment by CreativeMD** [comment]
Please download CreativeCore for 1.12.1 and not for 1.12
