### ISSUE TITLE
Prevents Applied Energistics 2 Quartz Seeds from performing in-world crafting.

### ISSUE THREAD

**Issue by VoilaTada** [CreativeMD/ItemPhysic#46]
#### Description
The Nether Quartz Seeds, Certus Quartz Seeds, and Fluix Seeds from Applied Energistics 2 usually slowly change into their pure versions when sitting in water. It appears that ItemPhysic is preventing them from progressing through this crafting behavior because it is changing the items into some other entity. I'm unsure if this problem is fixable within your mod or within AE2 (or at all), so I will be duplicating this issue on the AE2 repository as well. 

#### Environment
Multiplayer in the Mike's Excellent Skyblock Adventure pack: https://mods.curse.com/modpacks/minecraft/274895-mikes-exellent-skyblock-adventure

- Minecraft Version: 1.12
- ItemPhysic Lite Version: 1.3.7 mc1.12
- Forge Version: 2443
- AE2 Version: rv5-alpha-3

Applied Energistics 2 Issue relating to the same bug: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3056

**Comment by VoilaTada** [comment]
Not actually caused by Item Physic it seems. Further testing will be performed but I'm closing the issue because it's unrelated to this mod.

**Comment by CreativeMD** [comment]
Oh ok, i only remember that there used to be an issue, with ItemPhysic Full. The items would float on the top of the water and therefore not grow. You could easily fix that by placing a block above the water.

**Comment by VoilaTada** [comment]
We had that option off on our server, but they still wouldn't grow. We still didn't find the issue but Item Physic is definitely not the culprit, so rest easy. :)
