### ISSUE TITLE
Custom throw with Sponge vanishes items

### ISSUE THREAD

**Issue by Sonic2423** [CreativeMD/ItemPhysic#47]
If you drop any item selected with q (so "power" is displayed) the item isnt dropped but its gone. if you drop an item while looking at your inventory and drag and drop the item outside the inventory it doesnt vanish so this only happens with custom throw. when hovering with mouse over an item and pressing q also drops the item so it is only when dropping an item while pressing q in the world.
Log doesnt show anything on drop neither on server nor on client.
without sponge it works just fine.
with "B:customThrow=false" it still destroys/vanishes the item.

Running:
On Server:
forge-1.12.1-14.22.0.2444-universal.jar
CreativeCore v1.8.10 mc1.12.1.jar
ItemPhysic Full 1.4.7 mc1.12.jar
spongeforge-1.12.1-2444-7.0.0-BETA-2602

On Client:
forge-1.12.1-14.22.0.2444-universal.jar
CreativeCore v1.8.10 mc1.12.1.jar
ItemPhysic Full 1.4.7 mc1.12.jar

**Comment by CreativeMD** [comment]
Oh ... actually i fixed it already, but forgot to upload the new version for 1.12. It should be available soon now. Thanks for reporting this issue.
