### ISSUE TITLE
Crash (probably with Battle Towers)

### ISSUE THREAD

**Issue by ghost** [CreativeMD/ItemPhysic#48]
[crash-2017-10-23_16.47.07-client.txt](https://github.com/CreativeMD/ItemPhysic/files/1407330/crash-2017-10-23_16.47.07-client.txt)
i teleported somewhere on the map (-8000, 80, 8000) and everywhere was oceans, and there was a battle tower from atomicstryker, after 2 seconds i look around, it crashed..

**Comment by CreativeMD** [comment]
Does his fixes it?
https://www.dropbox.com/s/pzp0e0mytkdflqs/ItemPhysic%20Full%201.4.9%20mc1.12.2.jar?dl=1

**Comment by ghost** [comment]
hey ah, i'm late sorry about it. i just installed that jar and run the game then created a new world, and it crashed directly after world generation.
[crash-2017-10-27_20.47.47-server.txt](https://github.com/CreativeMD/ItemPhysic/files/1422950/crash-2017-10-27_20.47.47-server.txt)

**Comment by CreativeMD** [comment]
Could you send me the world?

EDIT
Wait i failed, could you redownload the file, now it should work.

**Comment by ghost** [comment]
yeah... the fresh world.. run and crashed only 1 time...
[New Ezterian World.zip](https://github.com/CreativeMD/ItemPhysic/files/1423004/New.Ezterian.World.zip)
and you can find the modpack in my github profile, as you know. its called Ezteria

**Comment by CreativeMD** [comment]
Have you redownloaded it?

**Comment by ghost** [comment]
when? xD i just downloaded it 1 time
oh i see your edit now... going to retry

**Comment by ghost** [comment]
uhm, i tried a few times about the teleporting thing and it didnt happen. so i think its fixed

**Comment by CreativeMD** [comment]
Ok, fix will be available soon. Thanks for reporting this issue.
