### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by XBagon** [CreativeMD/ItemPhysic#49]
Configurable damage on hit, when throwing items? That would be a lot of fun :D

**Comment by CreativeMD** [comment]
Thanks for this suggestion! I will add it to my todo list, but i will close this issue here, because it's obviously not an issue.

**Comment by XBagon** [comment]
I would have used the "Suggestion" label if I could. GitHub issues are used for suggestions a lot. Didn't know where to do it, so I tried this. 

Great!

**Comment by CreativeMD** [comment]
I know, but for me issues are issues and i want to solve all of them :P
