### ISSUE TITLE
[1.10.2, 1.11.2, 1.12.2] Fire from Igniting Items can erase/overwrite blocks

### ISSUE THREAD

**Issue by L-Clouds** [CreativeMD/ItemPhysic#50]
When the Igniting Items option is used, and a dropped item creates a fire, that fire can erase/overwrite a block, even non-flammable blocks.  This does not break the block, it is simply gone.

This happens when the igniting item is in the space of a block which is smaller than a full block.  For example, I have recorded a video with an Iron Fence, and an Ender Chest being destroyed:
https://streamable.com/x3fwf
(it is on top of an Ender Chest because it is shorter than a full block tall)

It can also destroy other mods' blocks such as item conduits and vacuum hoppers.

It happens in 1.10.2, 1.11.2, and 1.12.2.  I've tested:
ItemPhysic Full 1.4.6/CreativeCore v1.7.3 with Forge 12.18.3.2511
ItemPhysic Full 1.4.9/CreativeCore v1.9.13 with Forge 13.20.1.2579
ItemPhysic Full 1.4.9/CreativeCore v1.9.14 with Forge 14.23.1.2585

**Comment by CreativeMD** [comment]
Thanks for reporting this issue. It will be fixed in the upcoming version, which should be available soon.
 
Sorry, for not responding earlier, i was not at home the last days.

**Comment by L-Clouds** [comment]
Will there be a release for 1.10.2?  Because, people were noticing this problem in Project Ozone Lite which is for 1.10.2 and has your mod in it.

**Comment by CreativeMD** [comment]
should be available soon.
