### ISSUE TITLE
Suggestion: Vanilla Rendering Config

### ISSUE THREAD

**Issue by ChloeDawn** [CreativeMD/ItemPhysic#53]
I know it seems to go against half of this mods design, but I personally think it would be nice to have the option to disable the custom rendering; so the user can benefit from all of the custom throw/pickup, buoyancy, and flammability mechanics whilst still having the item entity render like it does in vanilla.

EDIT: If you have a dedicated place for suggestion tracking, let me know! This was just the first place I thought to post in.

**Comment by CreativeMD** [comment]
Thanks for your suggestion. Is added in v1.4.11. Sorry that it took me so long to respond, i was quite busy.
