### ISSUE TITLE
[Feature Request] Config to set all floating blocks/items in ItemPhysics Full

### ISSUE THREAD

**Issue by Fireztonez** [CreativeMD/ItemPhysic#54]
Hello,
I realy enjoy the Item Physics mod and is fit perfect with my pack based on reality Tech + Magi. But one thing is really missing is a config for add or remove blocks or items for the floating in water feature. I whant by example to set the sugar canes, the coal, all the tools in the game, etc.

I think for a mod adding items floating, is a necessity to have a config for that!

Fireztonez

**Comment by CreativeMD** [comment]
You can configure it using [IGCM](https://minecraft.curseforge.com/projects/ingameconfigmanager).

**Comment by Fireztonez** [comment]
Is it possible to change that configurations in a file?? Changing that in game take 100x more time than editing a simple file, is realy anoying to do that in game, when I can copy directly a complete inventory of item ID of item I whant to put in the config...

**Comment by CreativeMD** [comment]
I'm afraid but there is no other way at the moment :(
Furthermore you can't use item ids anymore.

**Comment by Fireztonez** [comment]
When I said ID's I want to said the name of item (example: minecraft:coal)

Can you add a way to change that in your config, I just try with IGCM, but sincerly is take realy to mutch time for that, is realy a nightmare. And the worst, that mod save all the change in a fucking NBT file, is realy not nice to edit a NBT file directly...

I have a lot of thing to do in my modpack, I have probably minimum 6 mount of work, without have to worry to change that's options, Sincerly, I realy like your mod, but if is impossible to change that with any other way, possibly I will need to look for something else, I can't work with IGCM (Is realy good for a basic user, but for a advance Modpack Dev, is realy not nice!!).

Thank's
Fireztonez
