### ISSUE TITLE
[Feature Request] Config what items are igniting

### ISSUE THREAD

**Issue by Efimero** [CreativeMD/ItemPhysic#55]
right now igniting items work great, but only vanilla torches do this, other torches like Primal Core ones don't
it would be great if it was just a list of items and we could add more form any mod, like blaze rods and blaze dust blocks, for example, and any other item

**Comment by CreativeMD** [comment]
You can do so using [IGCM](https://minecraft.curseforge.com/projects/ingameconfigmanager).
