### ISSUE TITLE
Items are hidden in snow layer

### ISSUE THREAD

**Issue by Snownee** [CreativeMD/ItemPhysic#56]
Possible to fix this problem?

![image](https://user-images.githubusercontent.com/16059084/42019445-c641c874-7ae7-11e8-850a-5b382f33960b.png)

This issue also happens to soulsand.

**Comment by CreativeMD** [comment]
I will try to implement a fix for it the next days.

**Comment by CreativeMD** [comment]
Released a fix for this on my discord server.
