### ISSUE TITLE
[Feature Request] Option to configure floating speed

### ISSUE THREAD

**Issue by Snownee** [CreativeMD/ItemPhysic#57]
Hi, I found the floating speed is too fast to catch swimming items after I installing ItemPhysic. Could you please add an option to customize this?

**Comment by CreativeMD** [comment]
Is it too fast or too slow? I will add an option for it anyway (hope to do it the next days)

**Comment by Snownee** [comment]
It is too fast. I can hardly catch items when I installed Streams.

**Comment by CreativeMD** [comment]
Oh, but that sounds like an issue of streams. Itemphysic makes wood and other floating materials float in water (up and down). It does not change anything about the speed of the streams. Maybe contact its author and ask him to implement a config option for the speed of streams?

**Comment by Snownee** [comment]
Oh I mean it can be a headache to catch up things in stream. As far as I know Streams doesn't tweak water speed. And this problem still occurs when Streams is not installed.

**Comment by CreativeMD** [comment]
Released a fix for this on my discord server. Thanks for you suggestion, there were a few bugs regarding this problem which I could finally fix now.

**Comment by Snownee** [comment]
Seems no release for ItemPhysic, or CreativeCore is enough? :thinking:

**Comment by CreativeMD** [comment]
Sorry, uploaded LittleTiles (twice) instead of ItemPhysic. Uploaded it now. You need CreativeCore and ItemPhysic.
