### ISSUE TITLE
[Help] NullPoint Exception with DoggyTalents v1.14.2.318 with CreativeCore_v1.9.25_mc1.12.2 and ItemPhysic_Full_1.4.13_mc1.12.2

### ISSUE THREAD

**Issue by NovaViper** [CreativeMD/ItemPhysic#59]
I'm getting a particular crash ever since CreativeCore and ItemPhysics updated. I've been trying to figure out the issue but have not been able to pinpoint a fix for it. I was wondering if you could help me pinpoint it (I didn't write this section of the code, which makes it all the harder to find a fix for it). You can see [issue 99 on the repo](https://github.com/ProPercivalalb/DoggyTalents/issues/99) for more details.

**Comment by percivalalb** [comment]
Fixed https://github.com/ProPercivalalb/DoggyTalents/commit/376dafcbdf748b760e9113925111a2b139953e11
