### ISSUE TITLE
Adding Burning Items?

### ISSUE THREAD

**Issue by joshmoni** [CreativeMD/ItemPhysic#6]
Is there anyway to add items to a 'burn list'? Its an amazing idea but there's certain mods that require items to burn in order for it to unlock stuff.

If not, is there a way to turn it off all together? Couldnt find anything in the configs.

**Comment by MrPotatoGaming** [comment]
I see a lot of mods use black-list overrides. Which would make everything burnable aside from what the user dictates?

**Comment by CreativeMD** [comment]
Yes, i will make this configurable :D

**Comment by CreativeMD** [comment]
Modders can add burning and swiming items, the configuration for CraftingManager will take some more time.
