### ISSUE TITLE
Suggestion: config option to allow all items to float.

### ISSUE THREAD

**Issue by Trinsdar** [CreativeMD/ItemPhysic#64]
I would like to be able to have all items float, but right now only wood items float.

**Comment by CreativeMD** [comment]
- Install [IGCM](https://minecraft.curseforge.com/projects/ingameconfigmanager)
- Type in `/ConfigManager`
- Navigate to `ItemPhysic` -> `Floating Items`
- Remove all existing entries, change from whitelist to blacklist
