### ISSUE TITLE
Different size between the item and its stack

### ISSUE THREAD

**Issue by wenlfs** [CreativeMD/ItemPhysic#65]
I'm having this tine bug with some items from Better with mods, the Planters with block, the Slats, the Grates and the Wicker. The single item and the item stack have different sizes.

ItemPhysic Full: 1.4.16
Forge: 14.23.4.2759

![2018-09-06_16 49 18](https://user-images.githubusercontent.com/41978516/45656636-f0b7de80-babc-11e8-9598-2499c97b9956.png)

Thank you!

**Comment by CreativeMD** [comment]
I reported this issue to the author of Better with mods, hopefully we can figure out how to fix it together (https://gitlab.com/BetterWithMods/BetterWithMods/issues/1244). I'm sorry that it took me so long to respond, I have been quite busy with other stuff.

**Comment by CreativeMD** [comment]
Fixed in v1.4.17, should be available soon.

**Comment by wenlfs** [comment]
Thank you.
