### ISSUE TITLE
Pickup Key always works using Shift

### ISSUE THREAD

**Issue by wenlfs** [CreativeMD/ItemPhysic#66]
When the key is set as none it works using shift and right-click, and if set as other key both will work, shift and the key that was set in the menu.

ItemPhysic: 1.4.16
CreativeCore: 1.9.32
Forge: 14.23.4.2759

**Comment by CreativeMD** [comment]
A sneaking player will always pickup items, so you don't have to collect every item by hand. I added an option to disable this behavior, which will be included in the upcoming version. I'm sorry that it took me way too long. Depending on how fast I can solve the other issue the new version will be uploaded today or tomorrow.
