### ISSUE TITLE
Suggestion: Swing Arm On Right Click

### ISSUE THREAD

**Issue by ChloeDawn** [CreativeMD/ItemPhysic#69]
It would add to the immersion if the player's arm were swung when right-clicking to pick up a dropped item. Currently the arm does not move, and the item is magically sucked towards them.

**Current version:** [1.4.17_mc1.12.2](https://minecraft.curseforge.com/projects/itemphysic/files/2629136)

**Comment by CreativeMD** [comment]
Thanks for this small but very important suggestions, those little things can make all the difference. (Will be part of the upcoming release).

**Comment by CreativeMD** [comment]
New version is out!
