### ISSUE TITLE
Suggestion: Option To Ignore Custom Pickup When Harvesting

### ISSUE THREAD

**Issue by ChloeDawn** [CreativeMD/ItemPhysic#70]
It would be nice to see an option that allows harvested drops to be automatically picked up by the player, to avoid the tedious step of mining, then manually picking up the item you just mined. I think this can be achieved through Forge's HarvestDropsEvent, but I haven't looked into it.

**Current version:** [1.4.17_mc1.12.2](https://minecraft.curseforge.com/projects/itemphysic/files/2629136)

**Comment by CreativeMD** [comment]
If you sneak the player picks up all items. Is that enough?

**Comment by CreativeMD** [comment]
Thanks for you suggestions will be part of ItemPhysic in the upcoming version release tomorrow.
