### ISSUE TITLE
Suggestion: Maximum Pickup Reach

### ISSUE THREAD

**Issue by ChloeDawn** [CreativeMD/ItemPhysic#71]
Currently with custom pickup, you can pick up items as far away as the player can reach blocks. From a realism perspective, this makes no sense for the arm to be able to reach that far to grab an item. It would be nice to see a config to control the maximum reach for being able to pick up an item with right-click.

**Current version:** [1.4.17_mc1.12.2](https://minecraft.curseforge.com/projects/itemphysic/files/2629136)

**Comment by CreativeMD** [comment]
Added it in the upcoming version, you can now even increase the distance to something like 100 :D
