### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by O13SC3N3** [CreativeMD/ItemPhysic#75]
Forge 2768
Latest Creative Core and Item Physics Full
Crash : https://pastebin.com/raw/feewH8aM

Item Physics Lite
Crash: https://pastebin.com/raw/dNnkLFjC

Not sure what's different, or exactly which mod is causing this. I had it working before but modpack launches with item physic is disabled.

**Comment by O13SC3N3** [comment]
I added 00_ to item physics lite, and the modpack launched. So Im assuming its a conflicting core mod?

Mods:
  00_ItemPhysic+Lite+1.3.7+mc1.12.2
  AkashicTome-1.2-12
  albedo-0.1.3
  alternatingflux-0.12.2-1
  angermanagement-1.0.0
  animania-1.12.2-1.6.2
  AppleCore-mc1.12.2-3.1.4
  AppleSkin-mc1.12-1.0.9
  Aquaculture-1.12.2-1.6.8
  armoryexpansion-0.2.0
  AutoRegLib-1.3-24
  autothirdperson-1.2.0
  backstab-1.12.2-1.0.3
  Baubles-1.12-1.5.2
  BetterCombat-1.12.2-1.5.6
  BetterDiving-1.12.2-1.0.7
  BetterFoliage-MC1.12-2.2.0
  BetterFps-1.4.8
  betternether-0.1.5-1.12.2
  BiomesOPlenty-1.12.2-7.0.1.2425-universal
  Blur-1.0.4-14
  Born+In+A+Barn+V1.8-1.12-1.1
  Botania+r1.10-358
  botaniatweaks-1.8.2
  Bountiful-2.0
  CarryOn+MC1.12.2+v1.12.1
  Ceramics-1.12-1.3.6
  Chameleon-1.12-4.1.3
  champions-1.12.2-1.0.3
  Clean+Prismarine+1.0
  ClientTweaks_1.12.2-3.1.11
  ClimaticBiomes-2.6.0-MC1.12.2
  ClimaticBiomes-DynamicTreesCompat-1.1.0-MC1.12.2
  ClocheCall-1.1.1
  ClockHUD-1.12-1.4.0
  Clumps-3.1.1
  CodeChickenLib-1.12.2-3.2.2.353-universal
  ColoredWater-1.12.2-b37
  conarm-1.12.2-1.2.2
  CookingForBlockheads_1.12.2-6.4.69
  coroutil-1.12.1-1.2.15
  CosmeticArmorReworked-1.12.2-v4
  CraftStudio-1.0.0.93-mc1.12-alpha
  CraftTweaker2-1.12-4.1.13
  CreativeCore_v1.9.35_mc1.11.2
  CTD-Core-1.12.2-1.4.1
  CustomMainMenu-MC1.12.2-2.0.9
  dailies-1.12.2-6
  desirepaths-1.12.1-1.2.3
  DoomlikeDungeons-1.12.0-MC1.12.2
  Dungeons2-mc1.12.2-f14.23.5.2768-v1.6.1
  DynamicSurroundings-1.12.2-3.4.10.6
  DynamicTrees-1.12.2-0.9.4
  DynamicTreesBOP-1.12.2-1.4.1e
  DynamicTreesPHC-1.12.2-1.4.2
  enchanting_tweaks-1.1.1
  endlesstraverse-1.12.1-0.0.4.1
  EnhancedVisuals_v1.2.1_mc1.12.2
  Exotic+Birds+1.12.2-2.2.1
  ExtraBotany-r1.1-50
  FamiliarFauna-1.12.2-1.0.11
  FancyBlockParticles-1.12.x-2.4.1
  FarmingForBlockheads_1.12.2-3.1.26
  FastFurnace-1.12.2-1.2.1
  FastWorkbench-1.12.2-1.6.0
  Ferdinand's+Flowers-1.12.x-1.10.4.1
  foamfix-0.10.3-1.12.2
  Forgelin-1.8.2
  ForgeMultipart-1.12.2-2.6.0.79-universal
  GottschCore-mc1.12.2-f14.23.5.2768-v1.6.0
  Harvest-1.12-1.2.7-20
  hooked-1.0.3
  hopperducts-mc1.12-1.5
  HungerInPeace-mc1.12-1.0.0
  HungerOverhaul-1.12.2-1.3.3.jenkins148
  HungerPersistence-mc1.12-1.0.1
  Hwyla-1.8.26-B41_1.12.2
  iblis-headshots-1.1.2
  iChunUtil-1.12.2-7.1.4
  IguanaTweaksReborn-1.4.5-mc1.12.x
  ImmersiveCables-1.12.2-1.3.2
  ImmersiveEngineering-0.12-88
  incontrol-1.12-3.8.3
  InitialInventory-3.0.0
  Inspirations-1.12.2-0.2.3
  instantunify-1.12.2-1.1.2
  inventory_x-1.12-1.0.2
  InventorySpam-1.12.0-1.0.3
  InventoryTweaks-1.64+dev.145
  IvToolkit-1.3.3-1.12
  JEHC-1.12.2-1.6.2.0
  jei_1.12.2-4.14.4.256
  JEIHider-1.1c
  jeiintegration_1.12.2-1.5.1.36
  JEROreIntegration-1.12.2-1.1.0
  journeymap-1.12.2-5.5.3
  JustEnoughIDs-1.0.2-26
  JustEnoughResources-1.12.2-0.8.10.50
  LibEx-1.12.2-1.0.8
  librarianlib-1.12.2-4.15
  llibrary-1.7.15-1.12.2
  lumen-Beta+0.4.1
  Mad+Villagers-1.12.2-1.0.1-release
  Mantle-1.12-1.3.3.39
  McAssistant-1.12.2-0.1d-beta
  minecraftboom-1.12.2-1.4.3-universal
  MobDismemberment-1.12.2-7.0.0
  modtweaker-4.0.15
  Mo-Glowstone-1.12.2-1.5.6
  MouseTweaks-2.9-mc1.12.2
  movinglightsource-1.12.2-1.0.15
  mowziesmobs-1.5.1
  MrTJPCore-1.12.2-2.1.3.35-universal
  MTLib-3.0.5
  MultiBags-0.0.5
  NaturalPledge-r3.0.2
  Neat+1.4-17
  netherbound-1.2
  netherchest-1.1.1
  Netherending-Ores-1.12.2-1.2
  NetherEx-1.12.2-2.0.8
  NetherPortalFix_1.12.1-5.3.17
  NoMobSpawningOnTrees-1.2.2-mc1.12.2
  nonerdpoles-1.12.2-1.2.3
  ore_stone_variants-4.3
  Pam's+HarvestCraft+1.12.2zb
  pamsimpleharvest-2.0.0
  PassableLeaves-1.12.2-2.0.0
  Peckish-1.12-1.1.0
  Placebo-1.12.2-1.5.0
  Plated-0.1.0
  PlayerRevive_v1.2.22_mc1.12.2
  plustic-7.0.0.0
  pmp-1.12.1
  PrettyBeaches_1.12.2-1.0.4
  ProjectRed-1.12.2-4.9.1.92-Base
  ProjectRed-1.12.2-4.9.1.92-compat
  ProjectRed-1.12.2-4.9.1.92-fabrication
  ProjectRed-1.12.2-4.9.1.92-integration
  ProjectRed-1.12.2-4.9.1.92-lighting
  ProjectRed-1.12.2-4.9.1.92-mechanical
  ProjectRed-1.12.2-4.9.1.92-world
  ProjectVibrantJourneys-1.12.2-1.5.2
  ProportionalDestructionParticles-1.12.2-1.2.4
  Quark-r1.5-144
  randompatches-1.12.2-1.11.0.3
  randomtweaks-1.12.2-2.4.0.7
  RecurrentComplex-1.4.7
  ResourceLoader-MC1.12.1-1.5.3
  Rex's-Additional-Structures-1.12.x+-(v.2.0.0)
  RoguelikeDungeons-1.12.2-1.8.0
  roughmobs2-1.12.2_2.0.12
  Ruins-1.12.2
  solcarrot-1.12.2-1.3.3
  SophisticatedWolves-1.12.2-3.13.7
  SoundFilters-0.10_for_1.12
  soundreloader-1.2-1.12.2
  SpartanShields-1.12.2-1.4.1
  stg-1.12.2-1.2.3
  StorageDrawers-1.12.2-5.3.8
  StorageDrawersExtras-1.12-3.1.0
  subh2o-1.12.2-1.5.6
  taiga-1.12.2-1.3.4
  TCFastCraftingMod-2.6-mc[1.12-1.12.2]
  TConstruct-1.12.2-2.12.0.113
  TinkeredHegemony-0.2.1
  tinkersarsenal-0.5
  TinkersComplement-1.12.2-0.3.0
  TinkersExtras-1.12.2-1.0.5
  tinkersjei-1.0
  TinkerSurvival-1.12.2-1.1.0.4
  TinkerToolLeveling-1.12.2-1.1.0
  Toast+Control-1.12.2-1.7.1
  tombstone-3.3.0-1.12
  ToughAsNails-1.12.2-3.1.0.139-universal
  Treasure2-mc1.12.2-f14.23.5.2768-v1.3.0
  tweakersconstruct-1.12.2-1.2.0
  UndergroundBiomesConstructs-1.12-1.3.1
  Unmending-1.0-1
  va-1.12.2-1.5.5
  VanillaFix-1.0.10-99
  VanillaTweaks-1.4.4
  VillageNames-1.12.2-2.0
  VillagerTrades-1.12-0.6.4
  villootgers_v1.0
  WailaHarvestability-mc1.12-1.1.12
  Wawla-1.12.2-2.5.265
  Waystones_1.12.2-4.0.67
  Wither+Skeleton+Tweaks-1.12.2-2.6.2
  wolfarmor-1.12.2-2.2.3.1798-universal
  worleycaves-1.3.0
  ZarakLIB
  zombieawareness-1.12.1-1.11.14

Java Arguments:
[-XX:MaxMetaspaceSize=300M, -XX:+UseFastAccessorMethods, -XX:+AggressiveOpts, -XX:+UseConcMarkSweepGC, -XX:+UseParNewGC, -XX:MaxGCPauseMillis=100, -XX:-DisableExplicitGC, -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses, -Dsun.rmi.dgc.server.gcInterval=600000, -XX:SoftRefLRUPolicyMSPerMB=5, -XX:MaxGCPauseMillis=50, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx5120m, -Duser.language=en]

**Comment by CreativeMD** [comment]
You are using CreativeCore 1.11.2, but you have to use the version for 1.12.2. That should fix your crash.

**Comment by O13SC3N3** [comment]
Wow, my bad. Question though. Why did adding 00_ to itemphysics allow the mod to work ?

**Comment by CreativeMD** [comment]
No? I think you have to change .jar to something else to disable the mod. Maybe something .jar_disabled.
