### ISSUE TITLE
Item Pickup Range Doesn't Support Below Reach Distance

### ISSUE THREAD

**Issue by ChloeDawn** [CreativeMD/ItemPhysic#76]
If the player can reach a block or entity, an item at that position can be picked up, even if the maximum pickup range is set to less than the player's reach distance / 5.0F.

Expected behaviour: Only allow the item to be picked up if it is within the maximum reach distance defined in the config, not the player's reach distance.

**Mod version:** [Full_1.4.18_mc1.12.2](https://minecraft.curseforge.com/projects/itemphysic/files/2663859)

**Comment by CreativeMD** [comment]
Oh right, fixed it. New version should be available soon.
