### ISSUE TITLE
Mined Drop Pickup Does Not Respect Pickup Range

### ISSUE THREAD

**Issue by ChloeDawn** [CreativeMD/ItemPhysic#77]
Mined drops are automatically picked up regardless of the maximum pickup distance defined in the config. I feel that it should respect that, and only auto-pickup items that could otherwise be manually picked up by the player. Maybe it could be its own config?

**Mod version:** [Full_1.4.18_mc1.12.2](https://minecraft.curseforge.com/projects/itemphysic/files/2663859)

**Comment by CreativeMD** [comment]
Yeah, forgot about that, added it now. Thanks!
