### ISSUE TITLE
[Suggestion] Pickup Sound For Mined Item Pickup

### ISSUE THREAD

**Issue by ChloeDawn** [CreativeMD/ItemPhysic#78]
It would be nice if the item pickup sound was played when mined drops are automatically added to the player's inventory.

**Current version:** [1.4.17_mc1.12.2](https://minecraft.curseforge.com/projects/itemphysic/files/2629136)

**Comment by CreativeMD** [comment]
Added it to the newest ItemPhysic version, which should be available soon. Thanks for your suggestions!

**Comment by ChloeDawn** [comment]
This appears to not be working in **v1.4.17_mc1.16.5**, drops are silently added when `pickupMinedImmediately` is enabled.
