### ISSUE TITLE
ItemPhysic interferes with Astral Sorcery's crystal anti-despawn mechanism

### ISSUE THREAD

**Issue by NolanSyKinsley** [CreativeMD/ItemPhysic#79]

**Comment by CreativeMD** [comment]
Does this version fixes it?
https://www.dropbox.com/s/lfjtqmmc2zz98dk/ItemPhysic_Full_1.4.20_mc1.12.2.jar?dl=1

**Comment by CreativeMD** [comment]
Actually this issue is not caused by ItemPhysic. I reported it to Forge, it might be a vanilla issue (don't know yet).
