### ISSUE TITLE
Freeze when dropping item into Minechem Liquids

### ISSUE THREAD

**Issue by MissPotato** [CreativeMD/ItemPhysic#8]
I'm going to say ahead of time, no crash-report is generated. The entire process just ceases up, and white screens. Nothing is dumped to console no "Server state STOPPED" or anything to that effect. And no new files inside the ~/crash-reports/ folder. I have also tried using F3+C to force a crash to no avail. Sorry I couldn't provide more useful information.

It also only seems to happen to chemicals that function like Magnesium;minechem:minechemElement:12. It seems to only be chemicals that have no flow. They also seem to act really odd when inside of minechem liquids that don't crash the game. They're shot through the ground at incredible speeds.  

I hope that is enough information to help you, its really hard to solve issues without a crash log.

**Comment by CreativeMD** [comment]
Yes :D never tested my physics on other fulls (only water and lava), but i have really no idea why the screen is freezing, i will do some testing. Hopefully i can fix this bug.

**Comment by CreativeMD** [comment]
So i could reproduce this bug, will start to fix this, maybe will be finished today.

**Comment by CreativeMD** [comment]
Contacted the author of Minechem, don't know if he will answers :D

**Comment by jakimfett** [comment]
Oi, thanks for pinging me about this. First things first...can you grab the latest build from the [Minechem Jenkins build server](http://jenkins.jakimfett.com/job/Minechem%201.7%20v5) and let me know if that fixes anything?

Secondly, could you turn on debug mode (from the Minechem config) and pastebin the last 100-200 lines from before the freeze?

Also...what is supposed to happen when the item gets dropped? I haven't played with the ItemPhysic mod, and I'm on my phone so I can't test it myself until later.

**Comment by CreativeMD** [comment]
this video is old, but shows what my mod should do http://www.youtube.com/watch?v=n5zRW0gJzNc
i will test these things soon :D

**Comment by CreativeMD** [comment]
Tested it and it's still there:
Also added some lines to find out when this is happening:
http://pastebin.com/EwPVPDF2

I found out that it stucks in these lines
http://pastebin.com/t0FHb9YA

**Comment by CreativeMD** [comment]
Issue is closed due to inactivity.
