### ISSUE TITLE
ItemPhysics causes items to frantically shake when placed into Astral Sorcery blocks .

### ISSUE THREAD

**Issue by zach2045** [CreativeMD/ItemPhysic#80]
I am currently running a server with Project Ozone 3. I noticed that whenever an item is placed into a structure from the Astral Sorcery mod, said item starts to shake rapidly in the structure rather than float above it like it should.

**Comment by CreativeMD** [comment]
Can you send me a screenshot of it? The main question is if the item spinning around is a highlighted or a regular one?

**Comment by zach2045** [comment]
![image](https://user-images.githubusercontent.com/33688064/54745667-ae687a80-4b8f-11e9-971d-9e89f684164d.png)
![image](https://user-images.githubusercontent.com/33688064/54745686-ba543c80-4b8f-11e9-98fd-f59bba21d659.png)
Here are some screenshots of a couple examples. Hopefully they help.

**Comment by CreativeMD** [comment]
Fixed in the newest Astral Sorcery update!
