### ISSUE TITLE
"pickupMinedImmediately" option not totally compatible with EDX Multipart (and possibly other Multipart mods?)

### ISSUE THREAD

**Issue by cosmicdan** [CreativeMD/ItemPhysic#83]
It seems when a multipart block is broken, unless it's the last remaining "part" of that block space, it will just drop into the world instead of adding to the inventory.

Full compatibility with EDX Multipart / MCMultiPart library would be great!

**Comment by CreativeMD** [comment]
Unfortunately that's not up to itemphysic. Multipart does not provide the drop, because it bypasses the entire system. I'm sorry but you will have to live with it.

Edit: i will upload the fix for other issue soon.

**Comment by cosmicdan** [comment]
What do you mean by "bypass", exactly? It doesn't fire the block harvest event (or w/e it's called these days, I can't remember)? If so then I guess that'd be a bug worth reporting to the EDX Multipart mod, right?

**Comment by CreativeMD** [comment]
HarvestDropsEvent yes, feel free to do so.
