### ISSUE TITLE
Crash with Crude Start

### ISSUE THREAD

**Issue by Avery93** [CreativeMD/ItemPhysic#85]
World gen of [A Crude Start](https://minecraft.curseforge.com/projects/a-crude-start) goes just fine, but the game immediately experiences a fatal error if the rock or stick items drop as a physics object, either by breaking or by dropping from the creative inventory:
>The game crashed whilst ticking entity
Error: java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block crude_start:rock, it is not an allowed value

(full error log [here](https://pastebin.com/WdRSnzRs))

Crash does not occur when block is simply destroyed in creative. This is pretty apparently an issue on the other mod's side, but they have no issue page and I have functionally no knowledge of java with which to comb through and see what the problem might be in their code. 

My proposed stop-gap solution: Is there any way to blacklist certain items/objects as not effected by this mod's physics? 

Version Info:
MC 1.12.2
Forge 14.23.5.2836
Item Physics Full 1.4.21

**Comment by CreativeMD** [comment]
The issue should be fixed, just update CreativeCore and it should work fine.
