### ISSUE TITLE
Crash with Kinetic Clear Lag.

### ISSUE THREAD

**Issue by ScienceDrummer** [CreativeMD/ItemPhysic#86]
I got a crash report that blames Clear lag, so I asked them about it and they said it was conflicting with this mod. They said there really isn't anything they can do, so I decided to bring it your attention.

https://paste.dimdev.org/acemunumim.mccrash

**Comment by CreativeMD** [comment]
Can you send me the log file?

**Comment by ScienceDrummer** [comment]
Have to upload on Discord since GitHub won't let me upload it here: https://discordapp.com/channels/256109634769780737/276752435869908993/584421088289882113

**Comment by CreativeMD** [comment]
It's a bukkit plugin? I'm very confused, I can't see any relations to my mod itemphysics. Can you send me the link of the issue? I suspect the authors know what's going on, so they might be able to help me.

**Comment by CreativeMD** [comment]
I will close this issue for now. Just reopen the issue if it still persists.
