### ISSUE TITLE
New Suggestion :D

### ISSUE THREAD

**Issue by KenyMylankca** [CreativeMD/ItemPhysic#88]
if u remember i suggested dropped burning items should burn the blocks that they can..lol

now i have new suggestion, if a gunpowder (or, plus; if you want exploding items too) drops on fire or lava block(or any burning block) so it explodes. it would be great :D hope u do it CreativeMD. 
Thanks!

**Comment by CreativeMD** [comment]
Added it to my todo list. Don't know when I will find time for it.

**Comment by KenyMylankca** [comment]
still waiting for this lovely thing... xD hope u have time to do it. thanks!

**Comment by CreativeMD** [comment]
Sorry I'm just very busy at the moment.
