### ISSUE TITLE
Spinning Thaumcraft items - Thaumcraft Compatability

### ISSUE THREAD

**Issue by WizardZartak** [CreativeMD/ItemPhysic#9]
Whenever I place an Item on any Thaumcraft pedestal, the item spins at a rapid speed in place. I haven't tried blocks though. Not only does it effect the items on pedestals, the Deconstruction tables seem odd; The thaumometer on top renders, misplaced, half way inside the block.

If this could some how be fixed, that would be great.

**Comment by CreativeMD** [comment]
I will contact the author

**Comment by CreativeMD** [comment]
The author replied maybe Thaumcraft will have an update pretty soon :D

**Comment by WizardZartak** [comment]
That's great! thanks for the response. ;)
