### ISSUE TITLE
Change pickup behavior to match Client-side configuration

### ISSUE THREAD

**Issue by Martmists-GH** [CreativeMD/ItemPhysic#90]
Some people have different preferences; We've come to a point where half the server wants to keep this mod, the others want to be able to pick up items normally. Please add a way to have the client choose the method for picking up items.

**Comment by CreativeMD** [comment]
Is IGCM installed?

**Comment by Martmists-GH** [comment]
Nope, does that mod fix this?

**Comment by CreativeMD** [comment]
What about being able to pickup items using right click and by walking over them?

**Comment by Martmists-GH** [comment]
Yeah, but configurable which one on client-side

**Comment by CreativeMD** [comment]
Can you try out this version?
https://www.dropbox.com/s/5ddz2jf0qj83xc7/ItemPhysic_Full_1.4.22_mc1.12.2.jar?dl=1

It adds an option "allowClientCustomPickup", if you set it to true. Each client can decide whether to use custom pickup or not.

**Comment by CreativeMD** [comment]
Are you still there?

**Comment by mmmilord** [comment]
Hey, sovlv from curseforge here. I tested it out on a fresh server/client config with only the 3 mods, CreativeCore, IGCM and ItemPhysic_Full_1.4.22. My server itemphysic.cfg goes as     B:allowClientCustomPickup=true
B:customPickup=false

As far as I can see it seems to work, when changing customPickup from the ingame configuration option from IGCM, the user can turn the feature off/on. I am yet to use it on my server with other mods so I can't say if there's any issues with it, but stand-alone it works great. Here is a video which will sum it up better. https://www.youtube.com/watch?v=vey6iSDmJr0&feature=youtu.be

Also, I am seeing some Z-Fighting, not sure if that's something on my end (I don't have any other mods) but I've only used the Lite version up until now and I can't remember seeing that happen so I'm not sure if that's a recurring problem.

**Comment by Parthurax** [comment]
> 
> 
> Are you still there?

Just tried it on my modded(160) Server and sadly it didnt worked.

**Comment by Parthurax** [comment]
Ah do i need IGCM to get this to work ? i tested without IGCM.

**Comment by Parthurax** [comment]
Dont work with IGCM either.

**Comment by mmmilord** [comment]
So I was testing it on my server with another player online, me turning the setting to true/false through IGCM on my own client affected the other players own settings, like it was globally being changed, as when I turned custompickup on for myself, threw items on them, they didn't pick it up, when I turned it off they'd automatically pull in items. Not really sure if I've set it up properly

**Comment by CreativeMD** [comment]
Ok let me explain. There is no synchronization of configuration between server and client if IGCM is not installed. Certain things are handled by the server other things by the client.

The server decides whether to pickup up items around the player. So if customPickup is enabled on the server, it will not pickup any items except if the player sneaks. The client handles the right click part. So if customPickup is disabled (on client) no message will appear and there will be no way to pick it up by right clicking it. Which means the client configuration is limited to the right click functionality and would not affect the sneaking part.

IGCM makes sure customPickup is the same on client and server, which obviously makes client side configuration impossible. So it would only work without IGCM.

The solution I suggested was a messy one and it doesn't make sense to continue it. What would be  required is a player based configuration on server side. Something I don't want to do at the moment. I will rewrite IGCM at some point to allow for more advanced configurations, but I don't know when I get to it.

So unfortunately there is no way to change the pickup behavior on client side (at least for now). Sorry :(

**Comment by mmmilord** [comment]
ah I see thanks for trying eitherway
