### ISSUE TITLE
[Dedicated Server Side] As soon the Item touch the ground it get deleted.

### ISSUE THREAD

**Issue by VirtualGaming1** [CreativeMD/ItemPhysic#92]
So I just got a Dedicated Server up and found out that it due to this or IGCM that as soon an Item form mining or dropping it to the ground it get deleted. I do not know what the cause is but here is what I am using.

MCForge: 14.23.5.2816
MC: 1.12.2
ItemPhysic Version: 1.4.21 full
IGCM Version: 1.2.10
Creative Core: 1.9.62

**Comment by CreativeMD** [comment]
IGCM enables you to configure stuff from various mods ingame. Pretty sure in this case, the despawn time of an item has been set to zero. So if you are an opped player type in `/ConfigManager` navigate to ItemPhysic and make sure the despawn time is set to 6000 (which is the default value).

**Comment by VirtualGaming1** [comment]
the despawn timer was not set to 0
There were no log of it ether and I deleted the ItemPhysic and IGCM configs to reset it but still delete on the ground. but for my other pack for some odd reason dose not do that and it have same mods as the one it is happening

**Comment by CreativeMD** [comment]
That is very weird and it does not happen if IGCM is not installed?

**Comment by VirtualGaming1** [comment]
It even dose that for some reason as well with out that.
I can take a look what different between the 2 servers because I think it might be a mod compact

**Comment by CreativeMD** [comment]
Very weird, the question is does it still occur without ItemPhysic?

**Comment by VirtualGaming1** [comment]
with out the mod it works normal at first I did not know what it was untill I disable ItemPhysic and it stop doing that. the only think is I left dropped Items on the ground and re-enabled the mod and they still there but it only effect when dropping to the ground. and here is another thing that I have a magic version of the same pack but with magic mod on it and that works fine so I must ran into a very rare issue. you know what just thinking about it while typing this is the non-magic was using BOP world gen setting but the other one if I remember right that is not. I'm going to do a test with it to confirm that.

**Comment by VirtualGaming1** [comment]
well still dose that and still no any kind of log about it ether.

**Comment by CreativeMD** [comment]
This is a very weird issue. Does it only happen in specific worlds (if yes can you send me them)?

I'm very confused how this bug can occur with only my mods installed :O

**Comment by CreativeMD** [comment]
Any news?

**Comment by CreativeMD** [comment]
Does this issue still persist?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists reopen it.
