### ISSUE TITLE
Server Crash on Startup

### ISSUE THREAD

**Issue by Nick-77ab2** [CreativeMD/ItemPhysic#93]
Using Item physics 1.4.21 and any version of Creative core with recommended forge version while running the RLCraft custom modpack
https://pastebin.com/F8LLUTmB
Crashes after patching item.entityitem

**Comment by CreativeMD** [comment]
Can you give me your mod list? Optionally you can also send the entire crash-report (all mods are listed there).

**Comment by Nick-77ab2** [comment]
Sorry for taking so long in responding. The modlist is straight from the RLCRAFT modpack. I can't do much on my end right now as I'm packing, I apologize for not being able to give much info. https://www.curseforge.com/minecraft/modpacks/rlcraft he gives a full list at the bottom.

**Comment by CreativeMD** [comment]
Can you send me the entire crash-report instead? Because something must be wrong otherwise it would not crash.

**Comment by Nick-77ab2** [comment]
So apparently it doesn't generate a crash report, but i can send the whole log.
FML-server-latest: https://pastebin.com/za49uBeh

Most noticeable line from above paste: 
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer com.creativemd.itemphysic.ItemTransformer@20d87335 from coremod ItemPatchingLoader

And here's the whole latest-log: https://pastebin.com/LCGVK59R
legitimately just that.

**Comment by CreativeMD** [comment]
There must be another mod which causes this issue. Can you try to figure out which mod it is (you can do so by removing some mods and see if it still crashes)?

**Comment by Nick-77ab2** [comment]
what's weird is that this seems to work and yet not work. For example: my friend had a server already set up for a different modpack, so he moved the RLCraft modpack and everything it needed over to that server and the server worked, more or less, without crashing due to conflicts. He sent it to me and it works. So technically this is a crash, but it also isn't. If that doesn't make sense, sorry. In answer to removing mods-> I've tried updating mods, i've tried removing mods, they both lead to different types of crashes. Now if these are crashes that are supposed to happen after the one i posted here, or if they're new crashes I don't know. The modpack is very unstable in the first place. I'll try again right now and see what i can do.

**Comment by CreativeMD** [comment]
You some mods require other mods, so you have to be careful which mod you are removing.

**Comment by Nick-77ab2** [comment]
ok so, some mods were missing, but what really was interesting was the fact that it's forge, not a mod that was the issue. I don't know what version of forge he was using, but it's a different size, as well as the version of minecraft 1.12 that it ran off of. The server works now, and the explanation for the crash is none other than forge itself.

**Comment by CreativeMD** [comment]
I tried it with the newest forge version and it works just fine.

**Comment by Nick-77ab2** [comment]
interesting. i'm pretty sure that's the version mine didn't work with. I can check it again, but this should be fine now.

**Comment by Nick-77ab2** [comment]
just realized what i thought, i was stupid and had forge 1.12 somehow. I've never made that mistake before, so i never thought about it. pretty sure i clicked the wrong thing on their updated UI.

**Comment by CreativeMD** [comment]
Oh right, glad you could figure it out! Hope you can enjoy the mod now.
