### ISSUE TITLE
Enable Igniting config not working 

### ISSUE THREAD

**Issue by Spiderfoxtail** [CreativeMD/ItemPhysic#94]
Hello, I have been trying to figure out why many buildings are catching fire on my server and we have traced it back to a feature of this mod. When torches are dropped, they cause fire on wooden structures, even with the following line set to false.

[[# If igniting items will be enabled or not. [default: true]
    B:enableIgniting=false]]

Just wondering if this is a glitch, or if there is some way to make dropped torches safe without having to remove this mod which is one of our favorites.

**Comment by CreativeMD** [comment]
Is IGCM installed?

**Comment by Spiderfoxtail** [comment]
Yes, we have that installed.

**Comment by CreativeMD** [comment]
Then you will have to disable it ingame. Type in `/ConfigManager` (can only be done by opped players) navigate to ItemPhysics and disable it there.

EDIT
IGCM will automatically synchronize the config across the entire server.

**Comment by Spiderfoxtail** [comment]
Thank you that has fixed it!
