### ISSUE TITLE
Magnetism makes items teleport

### ISSUE THREAD

**Issue by luxlacis** [CreativeMD/ItemPhysic#95]
Using the latest version of the mod and forge, when I use the magnetism staff from roots (and I assume it's the same with other magnet mods) the items just jump right to your feet instead of moving towards the player. This happens when the items have the new render when on the ground. Was wondering if it's possible to fix this and make the items move across the ground whilst they're moving towards the player.

**Comment by luxlacis** [comment]
This is the same in vanilla rendered mode

**Comment by CreativeMD** [comment]
Is it different without ItemPhysic installed?

**Comment by luxlacis** [comment]
It looks a little less sharp (jumpy) when it's without the mod but still quite instant, I believe it might actually be the Roots mod itself. It tried another plugin called Tiered Magnets and it's quite smooth actually. Sorry for the bother, I will contact the Roots developer.
