### ISSUE TITLE
Changed NBT Tags ?

### ISSUE THREAD

**Issue by Parthurax** [CreativeMD/ItemPhysic#98]
Im not sure if this is caused by your mod.
On some Items i have a NBT tag so i cant stack them. For example i got 20 bukets fill one with water and throw the water away and now i cant stack them anymore becouse something change with the NBT Tags.

This happens with a lot of items not every time but often.
jjust like i said im not sure if this is Itemphysics related but as far as i know its the only mod which changes items. This happens to Vanilla and Mod Items. Newest Version for 1.12

**Comment by CreativeMD** [comment]
This is not an issue of ItemPhysic, not sure why it's caused. Maybe try it out with only vanilla minecraft.
