### ISSUE TITLE
[suggestion] Item Destruction

### ISSUE THREAD

**Issue by mxnmnm** [CreativeMD/ItemPhysic#99]
Please make items getting destroyed by lava/cactus a config option

**Comment by mmmilord** [comment]
I think you have to use  IGCM

**Comment by mxnmnm** [comment]
O? I can enable item destruction using that mod?  I'll test it out later and if it works I'll close this issue.

**Comment by mxnmnm** [comment]
Considering IGCM is discontinued I think it's fair to ask that this becomes a feature within the mod

**Comment by mxnmnm** [comment]
Ok so looking a bit more closely at stuff creative core might be able to do stuff but I'll need to test

**Comment by mxnmnm** [comment]
Alright nice so I do see new configs now I missed before lol
